### ISSUE TITLE
Configurable full-screen grid size for widgets

### ISSUE THREAD

**Issue by Tertiush** [igorgladkov/rotini#100]
Hi

It would be nice to have the full-screen grid size for widgets configurable. This way the user has flexibility to customize the display to his/her liking, allowing for either more or less widgets that can be seen "at a glance" without scrolling.

On my 7" wall-mount tablet the widgets [with v0.5.41] are rather large relating to less usable real-estate for widgets per screen.

**Comment by Tertiush** [comment]
As per Igor's comment I will close this request:

> Igor Gladkov
> +Tertius Hyman​ It shows only 3 rows because there is just not enough screen space to fit 4 at minimum widget height. Widgets are designed to work at certain common minimum height, and they can't be shrinked further.

**Comment by igorgladkov** [comment]
@Tertiush While it won't be configurable, I will be revisiting grid widget sizing to find a possibility to make it closer to what it was before.

**Comment by Tertiush** [comment]
Thats fantastic news, thanks Igor. Must say I've grown accustomed to the new look already.....
