### ISSUE TITLE
Group gauge sizing issue when there is only two gauges

### ISSUE THREAD

**Issue by frode** [igorgladkov/rotini#101]
The following config makes the group with only two gauges render incorrect sized gauges.

![image](https://cloud.githubusercontent.com/assets/102189/15106375/2c49dd5e-15c9-11e6-85d3-f4110c411420.png)

Text label="RPi" {

  Frame label="Raspberry Pi {widget:gauge-group}" {
    Text item=memUsed label="{unit:MB,max:1024,icon:database}"
    Text item=cpuCombined label="{unit:%,icon:memory}"
    Text item=Raspi_temp label="{unit:deg,max:180,icon:memory}"
    Text item=openhabRealMem label="{unit:MB,max:1024,icon:database}"
  }
  Frame label="openHAB {widget:gauge-group}" {
    Text item=openhabRealMem label="{unit:MB,max:1024,icon:database}"
    Text item=openhabRealMem label="{unit:MB,max:1024,icon:database}"
  }

  }

**Comment by igorgladkov** [comment]
Fixed in 0.5.45
