### ISSUE TITLE
Calender Widget dumps when no location is assigned

### ISSUE THREAD

**Issue by michelde** [igorgladkov/rotini#102]
Hi Igor,

Reproduce: Load any calendar event where you didn't set a location.

Here is my item config for the calendar:

`String Haushalt1_Place "[%s]"                                            <calendar>  { caldavPersonal="calendar:haushalt type:EVENT eventNr:1 value:PLACE" } 
String Haushalt1_Title "Termin jetzt [%s]"                               <calendar>  { caldavPersonal="calendar:haushalt type:EVENT eventNr:1 value:NAME" } 
DateTime Haushalt1_Starttime "Beginn [%1$tT, %1$td.%1$tm.%1$tY]"         <calendar>  { caldavPersonal="calendar:haushalt type:EVENT eventNr:1 value:START" } 
DateTime Haushalt1_Endtime "Ende [%1$tT, %1$td.%1$tm.%1$tY]"             <calendar>  { caldavPersonal="calendar:haushalt type:EVENT eventNr:1 value:END" }`

My sitemap looks as follow:
`Frame label="{widget:calendar}" {
      Text item=Haushalt1_Title label="{item:event1-title}"
      Text item=Haushalt1_Place label="{item:event1-location}"
      Text item=Haushalt1_Starttime label="{item:event1-start-time}"
      Text item=Haushalt1_Endtime label="{item:event1-end-time}"
      Text item=Haushalt2_Title label="{item:event2-title}"
      Text item=Haushalt2_Place label="{item:event2-location}"
      Text item=Haushalt2_Starttime label="{item:event2-start-time}"
      Text item=Haushalt2_Endtime label="{item:event2-end-time}"
    }`

and this is the exception from openhab.log:

[openhab.log.zip](https://github.com/igorgladkov/rotini/files/258133/openhab.log.zip)

Once I deactivate the line with location in the sitemap it works again. I thing the widget should still work because I can't guarantee that every item has a location. 

Regards,
Michel

**Comment by igorgladkov** [comment]
@michelde Calendar widget does not require location to available (non empty) for every event, but it does require item to be set. Why would you want to not set location item?

**Comment by igorgladkov** [comment]
Closing as non-responsive. Feel free to reopen if it is still an issue.
