### ISSUE TITLE
Add "Sensor" widget info to wiki

### ISSUE THREAD

**Issue by TommySharpNZ** [igorgladkov/rotini#106]
Hey Igor, I noticed that I have some motion-sensor and door-sensor widgets in my sitemap which work just fine but I can't find anything on the wiki for them... I see they are still in the old "widget examples" files.

Would it make sense to have just one "sensor" widget and then we specify the correct icon if it is a door, window, motion, water etc?

Although I realise at the moment the icon for a window-sensor for example changes to red when the window is open... I guess you'd have to incorporate this somehow into the generic sensor too which could make it more complex... Maybe a way to specify 2 icons in the site map? Or maybe for every icon that could be used as a sensor behind the scenes you also have the red triggered version of the sensor icon?

I'm rambling a bit I guess....

**Comment by igorgladkov** [comment]
@TommySharpNZ There shouldn't be any different in icon behavior between generic sensor and specialized ones, all of them should have icon highlighted with red (or whatever color is from a theme), so I'm not exactly sure what did you mean here.
Main reason for "specialized" widgets is addition functionality in the future that would be possible only when the app "knows" what type of sensor it is.

**Comment by TommySharpNZ** [comment]
Okay cool... maybe then just this issue could be for updating the wiki with all the different "sensor" options?
