### ISSUE TITLE
Rotini crashes at start on Huawei MediaPad 7

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#107]
With the latest version (0.6.46) Rotini crashes when trying to start it on a Huawei MediaPad 7 with Android version 4.4.2. It worked with the previous Rotini version (0.5.44 or 0.5.42) but then crashed when I went into Settings and clicked on the OpenHAB server URL to change it. I've tried uninstall and reinstall it but no luck.

**Comment by igorgladkov** [comment]
@anordvall I pushed bug fix version that fixes this half hour ago, so it should propagate soon.

**Comment by anordvall** [comment]
Cool :D Thanks!
