### ISSUE TITLE
Rotini crashes when clicking on the Mode widget on a Huawei MediaPad 7

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#109]
In 0.6.50 on a Huawei MediaPad 7 with Android 4.4.2, Rotini crashes immediately when clicking on the Mode widget.

**Comment by igorgladkov** [comment]
@anordvall do you have PIN setup for that widget? There is an issue with PIN and 4.4, it isn't new to 0.6.50 though

**Comment by anordvall** [comment]
Yes I have a PIN for it. Ok I see. Looking forward to the fix :)

**Comment by igorgladkov** [comment]
Fixed in 0.6.51
