### ISSUE TITLE
Mode widget doesn't always trigger when selecting a mode

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#112]
If Rotini doesn't know the current state of the Mode widget (happens all the time due to the problems with server updates not reaching the client) nothing happens when clicking on the specific mode in the widget.

For example:

```
        Frame label="{widget:mode}" {
            Text label="{item:pin} [FtbrnEv2SK635YTnuTs1232oRZb+Jb0P3EOL1fLlVOc]"
            Selection item=AlarmMode mappings=[
                0="Off {icon:unsecure}",
                1="Perimeter alarm {icon:secure}"
            ]
        }
```

If Rotini thinks AlarmMode == Off, while in fact AlarmMode == Perimeter alarm, then I would expect that when clicking on the Mode widget and selecting Off, Rotini should always trigger an event so the alarm is in fact turned off. It should not depend on some client-side state.

**Comment by igorgladkov** [comment]
@anordvall Can you try this in the new version? I can't reproduce that behavior, but it might have been changed during the latest internal changes

**Comment by anordvall** [comment]
Hi @igorgladkov. I can still reproduce the same problem on 0.7.58. Anything I can do to help out with finding the root cause?

**Comment by igorgladkov** [comment]
@anordvall I'm actually re-reading your original post and I might understood it differently before.
Is this only a problem when in the app you tap on already highlighted mode?
So for example do you still have a problem in this case:
- server has state "mode1"
- the app has state "mode2"
  Then, either:
- you select "mode3" in the popup - does this work for you?
- you select "mode2" in the popup - this does not work, correct?

**Comment by anordvall** [comment]
> •you select "mode3" in the popup - does this work for you?
- Yes that works

> •you select "mode2" in the popup - this does not work, correct?
- You'r right. This does not work.

**Comment by anordvall** [comment]
In my case, when entering the house and the alarm signal tells me the alarm will go off in 20 seconds... I try to disable the alarm and nothing happens... To disable it then I first have to enable it (even though it is already enabled) and then disable it. Not good when you'r stressed because the alarm will go off any second :)

**Comment by igorgladkov** [comment]
Got it. Fixed for the next release.

**Comment by anordvall** [comment]
Many thanks :)

**Comment by anordvall** [comment]
Verified to work with the latest release. Thanks again!
