### ISSUE TITLE
PIN dialog doesn't fit on Galaxy S4 in landscape mode

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#113]
PIN dialog doesn't fit on Galaxy S4 in landscape mode.

![2016-05-22 15 37 14](https://cloud.githubusercontent.com/assets/13090236/15454241/1f7591bc-2033-11e6-9bfe-cf5d84ec580f.jpg)

**Comment by igorgladkov** [comment]
Fixed in 0.25

**Comment by anordvall** [comment]
Verified. Thanks!
