### ISSUE TITLE
Keep screen on, based on invisible widget

### ISSUE THREAD

**Issue by blddk** [igorgladkov/rotini#118]
I got an item in openhab switching ON when my phone is home, and OFF when it disappear from the network. I would love to use that to toggle the setting for keeping the screen always on.

Maybe it could be done with an invisible widget

```
Frame label="Keep screen on {widget:keep-on}" {
  Switch item=someoneIsHome
}
```

**Comment by blddk** [comment]
If people need it for multiple triggers, a rule can easily be made in openhab to handle different scenarios with multiple people, time, and so on.

**Comment by TommySharpNZ** [comment]
There have been a few discussions on this.... 
In general, I think being able to wake up the tablet and turn on the screen based on an OpenHAB item would be great. My use case would be using the lounge motion sensor to turn on the tablet and screen if it senses movement.
