### ISSUE TITLE
Widget Pin Security crashes Rotini

### ISSUE THREAD

**Issue by chrisncampbell** [igorgladkov/rotini#119]
Hello,

Have the following:

`Frame label="Timers {widget:switch}"
        {
            Switch item=timers
            Text label="{item:pin} [apW7q2PVh7WWOYxL1+kaEy8kAy0gB9EH5epxlncksJI]"
        }`

This happens with both the "switch" and "button-off" widgets, guessing others as well but didn't test.

When clicking the switch it crashes and closes Rotini. Any thoughts? Device is a Galaxy Tab 4 7", android 4.4

Thanks

**Comment by TommySharpNZ** [comment]
Yeah I only started having this issue when I reverted my tablet back to android 4.4.... Didn't have a problem when it was running 5.0

**Comment by igorgladkov** [comment]
Duplicate of #109
