### ISSUE TITLE
Multiple servers

### ISSUE THREAD

**Issue by welbymcroberts** [igorgladkov/rotini#12]
Allow the user to switch between multiple instances of openhab

**Comment by igorgladkov** [comment]
@welbymcroberts What is the use case of running multiple openhab servers (besides local/remote access)?

**Comment by welbymcroberts** [comment]
If a user has multiple properties they may want to have different instances, one per property.

**Comment by WafflesAreGreat** [comment]
I second this.  In addition to my home setup I also have a setup in the home of an elderly relative.  It would be nice to be able to switch between my home setup and their setup.

**Comment by igorgladkov** [comment]
https://plus.google.com/u/0/communities/110989367727284827143

> Would it be possible to define multiple servers as favorites? I have to instances running and always have to reenter the address.﻿

**Comment by spacemanspiff2007** [comment]
Hi Igor - any news yet?

**Comment by igorgladkov** [comment]
Added. Will be available in the new beta.
