### ISSUE TITLE
Crash on Android 4.4

### ISSUE THREAD

**Issue by johnjore** [igorgladkov/rotini#121]
Bought a cheap tablet and installed Rotini, after entering the hostname/ports for local/remote, the app crashes and closes. Send diagnostic data yesterday, June 5th @ approx 23:00 UK time. Would be great if this could be fixed.

JJ

**Comment by igorgladkov** [comment]
It seems like TLS cipher suite is the culprit here. From diagnostic data I see that cipher suite that is used is only supported starting from Android 5.0.
Do you have a limited ciphers enabled on the server?

That said, the app shouldn't be crushing in that case, so that would be a bug anyway.

**Comment by igorgladkov** [comment]
Upon further investigation it will probably work fine with the server after the crash is fixed in 0.7

**Comment by johnjore** [comment]
Thanks for looking into it so quickly, never suspected TLS/SSL being the culprit, and yes, switching to HTTP works fine, didn't even cross my mind. Its a standard RPI2 build using the standard cipher set the image came with so suspect others may hit the same issue at some point.

JJ
