### ISSUE TITLE
Autorefresh weather forecast widget

### ISSUE THREAD

**Issue by fsedarkalex** [igorgladkov/rotini#122]
I use a teblet which resides all the time on a docking station (switched on) and thus I noticced that the weather forecast widget does not autorefresh properly.

in detail it shows e.g. Mon, Tue and Wed and two days later it still shows Mon, Tue, Wed instead of Wed, Thu, Fri

//Edit: Restarting app leads to a refresh but I think this should automatically switch at midnight

**Comment by igorgladkov** [comment]
@fsedarkalex is it correct that only labels are broken, but actual forecast data did get updated?

**Comment by fsedarkalex** [comment]
Oh dient check that

Am 7. Juni 2016 18:02:35 MESZ, schrieb Igor Gladkov notifications@github.com:

> @fsedarkalex is it correct that only labels are broken, but actual
> forecast data did get updated?
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/igorgladkov/rotini/issues/122#issuecomment-224328410

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
