### ISSUE TITLE
How to write a item code for lights ON or OFF?

### ISSUE THREAD

**Issue by amarpulli1994** [igorgladkov/rotini#124]
Hello,
I am trying to do write code for lights.How to write the items code for lights ON or OFF?
here is my sitemap:

```
sitemap home label="OFFICE"
{
  Frame label="All Lights {widget:light-color-advanced}" {
        Colorpicker item=Light_GF_Office_Desk
    }
    Text label="Software Room" icon="icon"
    {
        Frame label="Lights {widget:light-switch}"
        {
            Switch item=SRoom 
        }

        Frame label="Bedroom Fan {widget:switch,icon:fan}" 
        {
          Switch item=Fan_Bedroom
        }
       Frame label="Bedroom Lights {widget:light-switch}" 
       {
          Switch item=Lights_Bedroom
       }    
    }
}
```

Thanks&Regards,
Amar.

**Comment by igorgladkov** [comment]
Amar, can you state what is the problem, what's not working? Your sitemap looks correct on first observation.

**Comment by amarpulli1994** [comment]
Hello,
How to control all lights ON or OFF with single button?like below screen shot
![screenshot-2](https://cloud.githubusercontent.com/assets/16384828/15960690/949dd536-2f1e-11e6-9ece-000609409d78.png)
Thanks & Regards,
Amar.

**Comment by igorgladkov** [comment]
Amar, you would just need to use a group that contains all lights with Light Switch widget, similar to what you have:

```
Frame label="All Lights {widget:light-switch}" {
  Switch item=Lights_All
}
```

and all your light switches would need be part of Lights_All group.

Let me know if this helps.

**Comment by amarpulli1994** [comment]
Hello,
I am try to do this can't getting this kind of control all lights with single light.please share your sitemap and item file along with this screen shot
![screenshot-2](https://cloud.githubusercontent.com/assets/16384828/15983643/4a49e304-2fcc-11e6-81ad-86457917f04a.png)

**Comment by igorgladkov** [comment]
@amarpulli544 to avoid any confusion, can you elaborate on what do you mean by "can't getting this kind of control all lights with single light," what is shown in the app: no widget at all, or widget is shown but not switching lights, or something else?

**Comment by amarpulli1994** [comment]
Hello,
Sorry sir,How to write sitemaps  and items along with screen shot?
![screenshot-2](https://cloud.githubusercontent.com/assets/16384828/15984112/d0464c58-2fdc-11e6-9abe-06e0cd933aa6.png)
Here is Iam writing sitemap file
 Text label="Lights"
     {
        Frame label="AllLights {widget:light-switch}"
        {
             Group item=AllLights 
        }
        Frame label="LivingRoom {widget:light-switch}"
        {
                          Switch item=light1
        }
        Frame label="Kitchen {widget:light-switch}"
        {
                    Switch item=light2
        }
        Frame label="BedRoom {widget:light-switch}"
        {
                       Switch item=light3
        }
        Frame label="BathRoom {widget:light-switch}"
        {
                       Switch item=light4
        }
        Frame label="Library {widget:light-switch}"
        {
                         Switch item=light5
        }
     }
But don't know, how to write items for this sitemaps ?
Thanks & Regards,
Amar.

**Comment by igorgladkov** [comment]
Items could go like this:

```
Group:Switch:OR(ON,OFF) AllLights "All Lights"
Switch light1 "Light 1" (AllLights)
Switch light2 "Light 2" (AllLights)
Switch light3 "Light 3" (AllLights)
Switch light4 "Light 4" (AllLights)
Switch light5 "Light 5" (AllLights)
```

**Comment by amarpulli1994** [comment]
Hello,
All lights control with single button is done.But ,what I am looking for item and sitemap file along with this screen shot.
![screenshot-2](https://cloud.githubusercontent.com/assets/16384828/15997147/32307606-314e-11e6-9c9a-2dd51ebdea62.png).
In this screen shot some lights is activated and some lights deactivated.How write the sitemap and item code getting this kind of screen shot.
please share this screen shot item and sitemap files.
Thanks & Regards 
Amar.

**Comment by igorgladkov** [comment]
Amar, state of switches in that screenshot is based on state of Switch item that you use in widget configuration.

all the code you showed and that I posted should allow you to get this sitemap. That screenshot was made months ago, so I don't have sitemap and items associated with that specific one.

Since you posted your sitemap that has all of that already, I'm not really sure why the question is still how to write that sitemap. I really struggling to understand the issue here.
