### ISSUE TITLE
How to get the widget pin security?

### ISSUE THREAD

**Issue by amarpulli1994** [igorgladkov/rotini#127]
Hello,
I trying to do widget pin seucrity.Here is my sitemap file
 Frame label="Lights {widget:light-switch}" 
     {
      Switch item=Lights
      Text label="{item:pin} [A6xnQhbz4Vx2HuGl4lXwZ5U2I8iziLRFnhP5eNfIRvQ]"
     }
how to configure the item file for widget pin security.
Thanks & Regards 
Amar.

**Comment by igorgladkov** [comment]
_Lights_ should be a regular switch item according to OpenHAB docs. This sitemap looks correct.

**Comment by amarpulli1994** [comment]
Hello,
How to configure the music player in your application.
Here is my sitemap file :
Text label="Music" icon="icon"
     {
        Frame label="{widget:music,size:fill}" 
        {
          Text item=Music_Track label="{item:track}"
          Text item=Music_Album label="{item:album}"
          Text item=Music_Artist label="{item:artist}"
          Text item=Music_Cover label="{item:cover}"
          Switch item=Music_Play_Pause label="{item:play-pause}"
          Switch item=Music_Skip_Next label="{item:skip-next}"
          Switch item=Music_Skip_Previous label="{item:skip-previous}"
          Setpoint item=Music_Volume label="{item:volume}"
          Switch item=Music_Mute label="{item:mute}"
        }
item file:
Switch Music_Play_Pause "music-play-pause" <music> (Music)
Switch Music_Skip_Next "music-skip-next" <music> (Music)
Switch Music_Skip_Previous "music-skip-previous" <music> (Music)
Number Music_Volume "music-volume" <music> (Music)
Switch Music_Mute "music-mute" <music> (Music)
The above code is working but the thing is how to play songs through your application.
In my device music player widget showing kile this
![screenshot_2016-06-13-15-59-49](https://cloud.githubusercontent.com/assets/16384828/16004640/58a3900c-3180-11e6-8b07-68b47ebc8c4a.png)
Thanks & Regards
Amar.

**Comment by igorgladkov** [comment]
Amar, the application doesn't actually plays songs, it just controls whatever music devices that you have. To configure that, I would suggest reading OpenHAB docs on related binding.
