### ISSUE TITLE
Scene widget using Switch items displays as Invalid config

### ISSUE THREAD

**Issue by qfluxlab** [igorgladkov/rotini#128]
Scene widget with below config displays as invalid with the message "At least 2 scenes are required for this size." I tried more switches up to 5 with no luck. It works fine using Selection item instead of switches.

App: 0.7.58
Android: 5.1.1

```
Switch  SW_DI_Welcome_Home      (gPersist)      [ "Switchable" ]
Switch  SW_DI_Goodbye           (gPersist)      [ "Switchable" ]

Frame label="House Mode {widget:scene}" {
    Switch item=SW_DI_Welcome_Home label="{icon:house}"
    Switch item=SW_DI_Goodbye label="{icon:door}"
}
```

**Comment by igorgladkov** [comment]
@dynostatic is that your exact items config? Because brackets in `[ "Switchable" ]` would make it an invalid configuration, so those items might be created and therefore wouldn't be available in the client.

**Comment by qfluxlab** [comment]
@igorgladkov I wondered about those tags causing a problem in the app, so I did try without them. I still get the same invalid config message. I restarted OH to make sure everything was initialized correctly after removing them.

The "Switchable" tags are used by the OH2 Hue Emulation binding. The items are created and working fine as switches in basic ui.

**Comment by igorgladkov** [comment]
@dynostatic I didn't realize that you are using OH2, because I was checking it on OH, which had it as syntax error. Will test on OH2 then.

**Comment by qfluxlab** [comment]
@igorgladkov I should have mentioned I was on OH2. Likely that is the problem. I ended up created a string item linked to my switches with rules to use in the widget for now until this is working.

**Comment by igorgladkov** [comment]
Closing since it would not be applicable to the new beta.
