### ISSUE TITLE
Feature request : PIN secured switch widget

### ISSUE THREAD

**Issue by hmerk** [igorgladkov/rotini#13]
As alreeady posted on G+, I would love to see a PIN secured switch for arming/disarming my alarm system.
When the user pushes the switch button, a PIN pad should popup and the item action should only be triggered after the correct PIN was entered and confirmed with an OK button.

Best
Hans-Jörg

**Comment by fsedarkalex** [comment]
you should remember that one could easily bypass that by accessing openhab directly so what's the clue?

**Comment by hmerk** [comment]
Only IF one could easily bypass it, but that's a complete different issue.
My aim is to have wall mounted tablets for controlling my smarthome and restrict those just to run a UI for that reason. The UI should implement such a security feature like it is implemented in imeriHome right now. This could either secure disarming alarm system or other features that should not be changeable by everyone, e.g children.

**Comment by fsedarkalex** [comment]
okay that sounds legit to me :)

**Comment by anordvall** [comment]
I would really like to see this as well for the same alarm use case.

I would suggest to pop up some nice keypad instead of as I believe ImperiHome do it, with popping up the native text input control. I might remember it wrong though...

**Comment by hmerk** [comment]
See my first post for this feature request. A keypad should be the preferred way. Just referred ImperiHome for explaining the use-case.

**Comment by igorgladkov** [comment]
Added in 0.3.28

**Comment by hmerk** [comment]
Great, Thanks @igorgladkov
