### ISSUE TITLE
Crashes from time to time since screensaver feature was introduced

### ISSUE THREAD

**Issue by igorgladkov** [igorgladkov/rotini#136]
> Since the last two versions (from the screensaver got introduced) the app stops and needs to be closed down and restarted from time to time. Happens multiple times during a day.
> 
> I'm running on a Asus TF101 which is rooted with Android 6.0.1﻿

https://plus.google.com/104419421211427773767/posts/hqsH44M9zZ1

**Comment by MrMontesa** [comment]
I'm facing these crahes as well. My device is a rooted cyanogenmodded Nexus 7 (2012). Some more details about my crashes can be found here: https://plus.google.com/104883187555375457281/posts/8hpa5sQFn7G

Let me know if I can assist in troubleshooting this issue? When I click "send crash report" is that something you receive?

**Comment by igorgladkov** [comment]
@MrMontesa Yes, I get those. Thanks for reporting.

**Comment by igorgladkov** [comment]
@MrMontesa Do you still experience crashes with screensaver in the latest version?

**Comment by MrMontesa** [comment]
I'm not using screensaver functionality at all.
After installing the latest version I came back from work and yes, rotini crashed. The rest of the evening and today I havent had any crash till now.
Also the "Try reconnect" errors are gone. Will closely monitor the behavior.

**Comment by igorgladkov** [comment]
@MrMontesa Do you have crashes in later versions?

**Comment by MrMontesa** [comment]
Hey @igorgladkov, can confirm that I dont have crashes in the most recent versions.
