### ISSUE TITLE
Button widget activates incorrect switch item?

### ISSUE THREAD

**Issue by TommySharpNZ** [igorgladkov/rotini#137]
Maybe it's just late and I'm missing something really simple here....

I've just created 3 button widgets on my main dashboard. The 3rd one should open the gate but when I press it then the "Garage 1" opens??? I have references to the item "Gate01Button" elsewhere in my normal OpenHAB sitemaps and they work just fine in the android app and classic UI for openHAB... 

```
Frame label="Garage 1 {widget:button-on}"{
        Switch item=Garage01Button label="[PRESS]"
        }
Frame label="Garage 2 {widget:button-on}"{
        Switch item=Garage02Button label="[PRESS]"
        }
Frame label="Gate {widget:button-on}"{
        Switch item=Gate01Button label="[PRESS]"
        }
```

**Comment by igorgladkov** [comment]
@TommySharpNZ Is your OpenHAB event log shows nothing for Garage01Button?

**Comment by TommySharpNZ** [comment]
Agh what! now that I try it this morning it all appears to be working just fine with the gate opening when I press the "Gate" button.

Must have been a cache or something...
