### ISSUE TITLE
Add RTSP Support to Camera Widget

### ISSUE THREAD

**Issue by webdes03** [igorgladkov/rotini#138]
Would it be possible to add support to allow RTSP streams in camera widget, ie: rtsp://{ip}:{port}/{stream}

**Comment by igorgladkov** [comment]
This might not be possible if OpenHAB backend proxy doesn't support rtsp. I know it didn't sometime ago, but didn't check lately.

**Comment by webdes03** [comment]
Perhaps we could work around that by just specifying {ip}:{port}/{stream} in the sitemap, or using a text property instead of a Video object? Just spit-balling ideas.

**Comment by igorgladkov** [comment]
While doable, in that case remote access through my.openhab will not work for one widget only, while everything else will work, so might be confusing.
Did you try making feature request for OpenHAB to support RTSP?

**Comment by webdes03** [comment]
I did not add that, though I'm also on OpenHAB 1 currently. I will submit that though... was just trying to find a bandaid solution. I see your side of it though.

**Comment by igorgladkov** [comment]
Closing since this is something that should be supported by the server.
