### ISSUE TITLE
Something like frames

### ISSUE THREAD

**Issue by fsedarkalex** [igorgladkov/rotini#15]
Just a feature request:

I would love having some equivalent to the Frames in normal sitemaps so we could order many widgets together like one row for weather, one for lighting, one for windows.
that is especially cool on tablets...

**Comment by igorgladkov** [comment]
@fsedarkalex Should you be able to do that now? Widgets are ordered horizontally in rows.
Maybe I'm not clear on the request, can you describe your use case in more details?

**Comment by fsedarkalex** [comment]
I mean that you could do this:

W1 W2 W3 W4
W5 W6
W7 W8 W9

**Comment by anordvall** [comment]
So, what you are looking for is really feature request in issue https://github.com/igorgladkov/rotini/issues/8 ?

**Comment by fsedarkalex** [comment]
well not completely I see you could use it the same way I forgot to mention an important detail above. I would also like to group items so you could say:

W1 W2 and W3 are a group. if you now have in first row already 3 items but only space for 5 items W1, W2 and w§ would go to second row (they should always be next to each other when possible)

but if issue 8 is implemented this one is nearly unneeded as you could do this manually then.

**Comment by igorgladkov** [comment]
1.0-beta1 will support any arrangement of widgets on a page through UI
