### ISSUE TITLE
Tasker plugin not populating anything

### ISSUE THREAD

**Issue by ubergeekseven** [igorgladkov/rotini#152]
Several versions ago i was able to use the tasker plugin, but it no longer populates anything. I do have several sitemaps, so, not sure if that's the issue. But i haven't seen anyone else say anything and not sure how many people use it, but it's a useful post of this app.

**Comment by igorgladkov** [comment]
Yes, there is a bug. Should be fixed in the next version.

**Comment by ubergeekseven** [comment]
Works again!

**Comment by derkens** [comment]
If I press "Select item" in the "Action configuration" in tasker, the list stays empty?

**Comment by igorgladkov** [comment]
@derkens What is the server version and the app version?

**Comment by derkens** [comment]
App: 0.17.89
Server: OH2 Snapshot 20/6

**Comment by derkens** [comment]
Just to inform you:
I've updated OH2 tot todays build (#417)
Nothing changed..

edit:
I see in the log:
`[WARN ] [o.myopenhab.internal.MyOpenHABClient] - Jetty request 8415 failed: null`
I'll try tonight when I am home on the local access.
See those same errors on location 'pushes' btw.

**Comment by derkens** [comment]
I'm sorry I havent reported back, but there is no difference on local or remote connection.

**Comment by igorgladkov** [comment]
Fixed in 0.20
