### ISSUE TITLE
location reporting - bug or config

### ISSUE THREAD

**Issue by derkens** [igorgladkov/rotini#155]
Location -> ON
Coordinates item = Dan_loc1
Address item = Dan_loc2

In my items file on oh2:
String  Dan_loc1 "Dan GPS [%s]"
String  Dan_loc2 "Dan adres [%s]"

then I checked the new help section:
I see the correct coordinates
I see the correct address

Under Last report I see "Unknown error" on both coordinates and address.

Location permissions granted.

Is there something else I can do to get it to work?

**Comment by igorgladkov** [comment]
I will be adding more specificity to some of those "unknown" errors, because currently if location report timeout while trying to reach a server it would go into unknown pile as well.

**Comment by igorgladkov** [comment]
Can you check what do you see in the latest release (0.25) for location report?

**Comment by derkens** [comment]
I feel a bit stupid now...
I still had the same error,
Failed (Time ago)
Error: unknown

Then I noticed the item for the voice notification and the path (/rest/items/....)
So I filled in the location item including the path.
Succes!
Maybe you can include this in the wiki or error reporting in Help?
Anyway, for me it is fixed, thank you for your app and your time.

**Comment by igorgladkov** [comment]
@derkens So before you have just item name, like "Location_Item" in configuration?
It should had a not found error in that case, weird.

**Comment by derkens** [comment]
Correct, just the item name
