### ISSUE TITLE
Room View Widget : Please add 4x1 and 4x2 size options?

### ISSUE THREAD

**Issue by TommySharpNZ** [igorgladkov/rotini#158]
Would it be difficult to add 4x1 and 4x2 to the new room view widget? Maybe allow up to 8 items in this size?

**Comment by igorgladkov** [comment]
I'm considering 4x sizes for some widgets throughout the app, if that goes forward then it should be possible to add these as well.

**Comment by igorgladkov** [comment]
Added in 0.27
