### ISSUE TITLE
Resizable widgets

### ISSUE THREAD

**Issue by fsedarkalex** [igorgladkov/rotini#16]
another feature request:

 think for some people it would be cool if qidgets would be zoomable. I don't mean resizable in particular but something like double size (is cool for tables at a wall showing current weather along with some switches but there weather should be big and readable from far distance)

(I hope you don#t mind me flooding you with ideas :) )

**Comment by anordvall** [comment]
I support this request. I have a tablet (soon to be wall mounted) and I have a 3x2 sized clock in the sitemap. Next to it I would like to have the temperature widget in size 2x2 (or 1x1 and just zoomed to twice the size). However, currently temp widgets can only be 1x1 and that's unreadable from the couch.

**Comment by tbrandstetter** [comment]
I would like to see auto resizing boxes which are resizing in width and height, so that they're filling the whole viewport space (no matter what device you're using). I know this is somewhat ambitious but it would be great.

**Comment by igorgladkov** [comment]
@tbrandstetter Is config "size:fill" would do what you want?

**Comment by tbrandstetter** [comment]
@igorgladkov If this means that I can have multiple widgets on one page with the value "fill" wo then resize according to the available space - yes :+1:

**Comment by igorgladkov** [comment]
@tbrandstetter well, no, fill works only for one widget (for widgets that do support it). I'm not quite clear on what are you trying to achieve then, can you talk more about your layout?
Widgets do fill screen horizontally based and then vertically if there is enough of them to fill.

**Comment by tbrandstetter** [comment]
@igorgladkov as an example, on an 5 inch smartphone you can have 3 1x1 blocks in a row and (i don't know it exactly - because I doesn't have one) 5 1 x blocks underneath. On a bigger tablet (for example an old nexus 7 2012 as I have) you can have 4 1 x 1 blocks in a row and 6 1 x 1 blocks underneath. 

If there is no autoresizing of the 1x1 blocks you have a different view on the phone and on the tablet. Means, you need two different sitemaps (one for the phone and one for the tablet).

**Comment by igorgladkov** [comment]
@tbrandstetter I don't think there is a way around having multiple sitemaps if you really want to cover all screen on each device. Stretching all 1x1 switches doesn't look good and most of the time there is no way to know what is the intention of any given sitemap layout on all screens.
As an example, phones (handheld) most of the time will have content scrolling vertically and that's okay to use. While tablets on the wall shouldn't really have any scroll for better interaction.

**Comment by tbrandstetter** [comment]
Maybe you're right. That's why I also vote for the "empty" widget feature :-) which "for me" is some kind of workaround to use bigger screens more efficiently.

**Comment by igorgladkov** [comment]
All widgets are resizable in 1.0-beta1
