### ISSUE TITLE
Window Blinds widget - Invert value

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#167]
In habDroid I have to use invert_percent in the item to make it work properly. However, when having this it doesn't work properly in Rotini. Rotini then says CLOSED when it's in fact open, and e.g. 20% OPEN when it's in fact 80% open.

Perhaps this is an issue in habDroid (I don't know), but would it be possible with some widget specific option to invert this in Rotini as well? Then I could keep my current item configuration to still support habDroid (which my wife uses on her iPhone) and also have it working properly in Rotini.

This is my item zwave config to make it work good in habDroid:
zwave="41:command=switch_multilevel, invert_percent=true"

**Comment by fridomac** [comment]
I use Rollershutter switches from RWE, and have the same issue. All my items use the "param=rollershutterinverted"-Parameter, which is present on both Z-Wave and RWE Rollershutters, I believe.

Bye, Frido.

**Comment by igorgladkov** [comment]
Honestly, I don't know why habdroid or other UIs use values in the reverse to begin with. The underlying number values (0 - closed, 100 - open) seem to make sense.
In any case, I will look into this.

**Comment by hmerk** [comment]
This is not an issue of the UIs, its an architectural issue within openHAB.
The same thing happens with my digitalSTROM devices.
openHAB treats 0% as open and 100% as closed.

**Comment by MrMontesa** [comment]
Same here using Homematic rollershutters. The value is inverted as well. 90% means nearly closed.
Heres my item config in case this might help:

```
Rollershutter og_leonie_rolladen
    "Rolladen Leonie [%d %%]"
    <rollershutter>
    (gOG_Rollaeden)
    {homematic="address=LEQ1234567, channel=1, parameter=LEVEL"}

```

**Comment by igorgladkov** [comment]
Added in 0.23
