### ISSUE TITLE
Clock widget

### ISSUE THREAD

**Issue by fsedarkalex** [igorgladkov/rotini#17]
Last idea for now:

I would love to see a clock widget which is double the normal widget width.
It should display the current time (HH:MM:SS) and ticker up automatically.
Of course the time could be taken from android then for traffic and corectness.
Idea: You could add a kind of a flag for the user to determine if they want server or android time...

**Comment by igorgladkov** [comment]
@fsedarkalex so the difference from current clock widget is that you want larger font and showing seconds?
Also, what are the benefits of having time coming from server? Is it because different timezones can be possible?

**Comment by fsedarkalex** [comment]
I ma just thinking universal. There is no particular reason for me suggesting server time.
I did not otice there is already a clock but yes the size matters for me here as  am using a 10.1 inch tablet mounted at a wall as weather station and main smart home control.

**Comment by fsedarkalex** [comment]
Frame label="{widget:clock,size:3x2}"
I verified having latest version (with the new changelog for 0.2.16 displayed) but the widget does not size bigger than 2*1

**Comment by fsedarkalex** [comment]
sorry! Works! My fault...
