### ISSUE TITLE
Invalid state "OFF" for window-sensor widget.

### ISSUE THREAD

**Issue by derkens** [igorgladkov/rotini#174]
Item has invalid state: "OFF"
Sitemap:
`Frame label="Keukenraam {widget:window-sensor}" {
        Text item=Powermax_zone5_status
        }`
If I change window-sensor to door-sensor, it works ok.

**Comment by igorgladkov** [comment]
What is the config for `Powermax_zone5_status` item?

**Comment by derkens** [comment]
The config (item config) is:
`Switch Powermax_zone5_status "Keukenraam" (GPowerMax, gP_kitchen) {powermax="zone_status:5", autoupdate="false"}`
I'm using the switch item because the contact item has a translation in the config.

**Comment by igorgladkov** [comment]
Fixed in 0.25
