### ISSUE TITLE
Enhancement for Colorpicker widget

### ISSUE THREAD

**Issue by fsedarkalex** [igorgladkov/rotini#18]
Ha! I got another one!

You have some free space at your color picker so you could add a bigger complete white and complete black button somewhere at the corners if you'd like :)

I would like it for my setup but don't want to stress you too much for my own little personal whishes :dash:

**Comment by igorgladkov** [comment]
New [Light Color Advanced](Light-Color-Advanced-Widget) widget should cover this.
