### ISSUE TITLE
Widgets update issue (bug)

### ISSUE THREAD

**Issue by giig1967g** [igorgladkov/rotini#184]
Hi Igor,
just wanted to report a bug.

If wifi connection disconnects and then reconnects, the widgets are not updated automatically anymore. You need to manually update them.

To replicate it just do this:
- Make sure Rotini is not working in the background
- Start Rotini
- Make sure everything is working and that Rotini gets the updates
- Now, disable the wifi connection in your tablet
- Wait few seconds and then reconnect the wifi connection.
- Go into Rotini and you will see that the widgets do not get updated automatically anymore

If you force shutdown Rotini and restart it , everything works again as normal.

**Comment by igorgladkov** [comment]
Obsolete since 1.0 Preview
