### ISSUE TITLE
Home-Assistant support

### ISSUE THREAD

**Issue by thundergreen** [igorgladkov/rotini#186]
Hi! I jooined the program and tried to connect to my Home-Assistant instance but there'ss only OpenHab. How can i get this running for Home-Assistant?

**Comment by igorgladkov** [comment]
Home assistant is not supported by current version. HASS support was just announced few days ago. Current target is to release it within a couple of months.
Stay tuned for announcements in G+ community.

**Comment by igorgladkov** [comment]
Will be available in 1.0-beta1
