### ISSUE TITLE
Back arrow when using voice commands

### ISSUE THREAD

**Issue by Flole998** [igorgladkov/rotini#188]
When i use voice commands it switches to the Page for voice recognition but there is no back arrow in the upper left corner. As i have a Tablet mounted in the wall I do not have access to the hardware buttons and therefor have no way of exiting out of there. Everywhere else in the App it seems to be optimized for my purpose, just that one thing is different.

**Comment by anordvall** [comment]
I would suggest not having to go to a different view at all for voice commands. See the "standard" openHAB app where this works perfectly.
