### ISSUE TITLE
Unable to connect openHAB sever from android app?

### ISSUE THREAD

**Issue by amarpulli1994** [igorgladkov/rotini#189]
I am trying do connect your android app to openhab sever, but i am unable access sitemaps. While accessing sitemaps ,android app  showing error like this...,
![screenshot_20161129-140310](https://cloud.githubusercontent.com/assets/16384828/20702218/ebda7f16-b63c-11e6-8359-063a1d233014.png)
How to solve this error? Please help me......
This is my sitemap file:
sitemap home label="HOME"
{
	 
Frame label="{widget:clock,size:3x2}"
	 
	 
Text label="Lights"
	 {
  		
Frame label="AllLights {widget:light-switch}"
		
{
			
 Group item=AllLights 
	
	}
		
Frame label="LivingRoom {widget:light-switch}"
		
{
             Switch item=light1
		
}
		
Frame label="Kitchen {widget:light-switch}"
		
{
            
 Switch item=light2
		
}
		
Frame label="BedRoom {widget:light-switch}"
		
{
     
        Switch item=light3
		
}
		
Frame label="BathRoom {widget:light-switch}"
		
{
             Switch item=light4
		
}
		
Frame label="Library {widget:light-switch}"
		
{
             Switch item=light5
		
}
	 
}
	 
Text label="Cellar" icon="icon"
	
 {
	 	Frame label="Car {widget:light-switch}"
	 	{
	 		Switch item=car
	 	}
	 	Frame label="GateLights {widget:light-switch}"
	 	{
	 		Switch item=gatelights
	 	}
	 	Frame label="Gate {widget:light-switch}"
	 	{
	 		Switch item=gate
	 	}
	 	Frame label="GarageDoor {widget:light-switch}"
	 	{
	 		Switch item=garagedoor
	 	}
	 	
	 }
	  Text label="Hall" icon="icon"
      {
   	  
   	  Frame label="Home Theater {widget:scene,size:2x1}" 
   	  {
       	Selection item=Harmony_Activity mappings=[
      	"TV"="TV {icon:tv}",
   		"Blue-ray Player"="Blue-ray {icon:playstation}",
    	"PowerOff"="OFF {icon:switch}",
    	"Nexus"="Nexus {icon:gamepad}",
    	"Chromecast"="Chromecast {icon:cast}"]
		}
	  Frame label="Lights {widget:light-switch}"
	  {
			 Switch item=Hall_lights 
	  }
	  Frame label="Fan {widget:switch,icon:fan}" 
	  {
             Switch item=Hall_fan
      }
	  Frame label="Refrigerator {widget:switch,icon:refrigerator}"
   	  {
   		Switch item=Refrigerator
   	  }
   	  Frame label="Wifi {widget:switch,icon:wifi}"
      {
        	Switch item=Wifi
      }
      Frame label="Computer {widget:switch,icon:wifi}"
      {
        	Switch item=Computer
      }
      
      Frame label="TV {widget:switch,icon:wifi}"
      {
        	Switch item=TV1
      }
      Frame label="Door {widget:switch,icon:wifi}"
      {
        	Switch item=HallDoor
      }
      Frame label="Window {widget:switch,icon:wifi}"
      {
        	Switch item=HallWindow
      }
      Frame label="AC{widget:switch}"
   	  {
   	    	Switch item=Hall_AC
   	  }
   	    Frame label="Laundry{widget:switch}"
   	  {
   	    	Switch item=laundry
   	  }
   	  Frame label="BoomBox{widget:switch}"
   	  {
   	  	    Switch item=Boombox
   	  }
   	  Frame label="Lock{widget:switch}"
   	  {
   	  	    Switch item=lock
   	  } 
   	  
   }

   Text label="BedRoom1" icon="icon"
   {
   	    Frame label="BedRoomAllLights{widget:light-switch}"
        {
             Group item=BedRoomAllLights 
		}
		
		Frame label="Lights {widget:light-switch}"
		{
			 Switch item=lights 
		}
		
		Frame label="Bedroom Fan {widget:switch,icon:fan}" 
		{
             Switch item=Fan_Bedroom
        }
       
         Frame label="TV {widget:switch,icon:wifi}"
        {
        	Switch item=TV1
        }
        Frame label="AC{widget:switch}"
   	    {
   	    	Switch item=AC
   	    }
        Frame label="Refrigerator {widget:switch,icon:refrigerator}"
   	    {
   		    Switch item=Refrigerator1
   	    }
   	    Frame label="BedRoom Door {widget:switch,icon:wifi}"
        {
        	Switch item=Door
        }
        Frame label="Window {widget:switch,icon:wifi}"
        {
        	Switch item=Window
        }
         Frame label="Candle {widget:light-switch}" 
        {
             Switch item=Candle
        }
        Frame label="BathRoom Lights {widget:light-switch}" 
        {
             Switch item=Lights_Bedroom1
        }
         Frame label="BathRoom Door {widget:switch,icon:wifi}"
        {
        	Switch item=Door1
        }
         Frame label="Geaser {widget:switch,icon:wifi}"
        {
        	Switch item=Geaser
        }
	
   }
   Text label="BedRoom2" icon="icon"
   {
     	Frame label="BedRoomAllLights{widget:light-switch}"
        {
            Group item=BedRoomAllLights2
		}
     	Frame label="Lights {widget:light-switch}"
   	    {
   		    Switch item=Lights
   	    }
   	    Frame label="Bedroom Fan {widget:switch,icon:fan}" 
		{
             Switch item=Fan_Bedroom2
        }
       
        Frame label="TV {widget:switch,icon:wifi}"
        {
        	Switch item=TV2
        }
        Frame label="Refrigerator {widget:switch,icon:refrigerator}"
   	    {
   		    Switch item=Refrigerator2
   	    }
   	    Frame label="AC{widget:switch}"
   	    {
   	    	Switch item=AC2
   	    }
   	    Frame label="BedRoom Door {widget:switch,icon:wifi}"
        {
        	Switch item=Door2
        }
        Frame label="Window {widget:switch,icon:wifi}"
        {
        	Switch item=Window2
        }
         Frame label="Candle {widget:light-switch}" 
        {
             Switch item=Candle2
        }
        Frame label="BathRoom Lights {widget:light-switch}" 
        {
             Switch item=Lights_Bedroom2
        }
        Frame label="BathRoom Door {widget:switch,icon:wifi}"
        {
        	Switch item=BathDoor
        }
        Frame label="Geaser {widget:switch,icon:wifi}"
        {
        	Switch item=Geaser2
        }
    }  
   
 }
This is my Item file:

Group:Switch:OR(ON,OFF) AllLights "All Lights" 
Switch light1 "Light 1"  <icon> (AllLights)
Switch light2 "Light 2"  <icon> (AllLights)
Switch light3 "Light 3"  <icon> (AllLights)
Switch light4 "Light 4"  <icon> (AllLights)
Switch light5 "Light 5"  <icon> (AllLights)

Group:Switch:OR(ON,OFF) Refrigerator "refrigerator" <refrigerator> (otherGroups)
Number Harmony_Activity "harmony-activity"
Switch TV "TV"
Switch PowerOff "PowerOff"
Switch Nexus "Nexus"
Switch Chromecast "Chromecast"
Switch Wifi "Wifi" <wifi> (otherGroups)
Switch TV3 "TV3" <tv> (otherGroups)
Switch HallDoor "HallDoor" <door> 
Switch HallWindow "HallWindow" <window>
Switch Hall_lights "Hall_lights " <icon>
Switch Hall_fan "Hall_fan" <fan>
Switch Computer "Computer" <computer>
Switch Hall_AC "Hall_AC" <ac>
Switch laundry "laundry" <laundry>
Switch Boombox "Boombox" <boombox>
Switch lock     "lock"	 <lock>

Group:Switch:OR(ON,OFF) BedRoomAllLights "BedRoom All Lights"
Switch lights "lights" <icon>( BedRoomAllLights )
Switch Fan_Bedroom "Fan_Bedroom"<fan> ( BedRoomAllLights )
Switch Lights_Bedroom1 "Lights_Bedroom1" <icon>( BedRoomAllLights )
Switch AC "AC" <ac> (BedRoomAllLights)
Switch Refrigerator1 "Refrigerator1" <refrigerator>( BedRoomAllLights )
Switch Door "Door" <door> (BedRoomAllLights)
Switch Window "Window" <window> (BedRoomAllLights)
Switch TV1 "TV1" <tv> (BedRoomAllLights)
Switch Candle "Candle" <candle> (BedRoomAllLights)
Switch Door1 "Door1" <door> (BedRoomAllLights)
Switch Geaser "Geaser" <geaser> (BedRoomAllLights)

Group:Switch:OR(ON,OFF) BedRoomAllLights2 "BedRoom All Lights2"
Switch Lights "Lights" <icon>( BedRoomAllLights2 )
Switch Fan_Bedroom2 "Fan_Bedroom2"<fan> ( BedRoomAllLights2 )
Switch Lights_Bedroom2 "Lights_Bedroom2" <icon>( BedRoomAllLights2 )
Switch Refrigerator2 "Refrigerator1" <refrigerator>( BedRoomAllLights2 )
Switch Door2 "Door2" <door> (BedRoomAllLights2)
Switch Window2 "Window2" <window> (BedRoomAllLights2)
Switch TV2 "TV2" <tv> (BedRoomAllLights2)
Switch Candle2 "Candle2" <candle> (BedRoomAllLights2)
Switch BathDoor "BathDoor" <door> (BedRoomAllLights2)
Switch Geaser2 "Geaser2" <geaser> (BedRoomAllLights2)
Switch AC2 "AC2" <ac> (BedRoomAllLights2)

Switch car "car" <car>
Switch gatelights "gatelights" <icon>
Switch gate "gate" <gate>
Switch garagedoor "garagedoor" <garage>

**Comment by igorgladkov** [comment]
Obsolete after 1.0-beta1
