### ISSUE TITLE
Hardware menu button does not open the menu

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#19]
Currently (at least on Galaxy S4) if I enable Full Screen Mode in settings, I can no longer access the settings page to turn it off. Instead I have to go to device settings to clear the data and re-open the app.

Would be good if the Menu hardware button on the phone would pop up the menu.

**Comment by igorgladkov** [comment]
@anordvall Menu should still open with the swipe from the left edge of the screen (it does that even without full screen). Can you try that?

**Comment by anordvall** [comment]
Hi Igor,

Ah I see! :) I can confirm it works, thanks!

Still, I hope you can also tie it to the hardware button as I'm sure I'm not the only person who would get stuck on this ;)

Anyway, thanks for a great app and your quick responses to everyones questions and requests!

**Comment by igorgladkov** [comment]
Out of curiosity, are you using Android or iOS devices for day-to-day use?
I was under impression that edge-swipe is universal gesture for Android users to get to navigation drawer, but you can prove me wrong ;)

**Comment by anordvall** [comment]
I'm using Android and have been for several years. I now realize I've used edge-swipe a lot before so I should of course have tried that when the menu button didn't work. I guess I just assumed there was a bug when nothing happened when hitting menu :)

**Comment by igorgladkov** [comment]
I see. I myself haven't used many phones with hardware menu buttons lately, so totally forgot about it.

**Comment by anordvall** [comment]
Verified. Thanks! :)
