### ISSUE TITLE
Idea for Weather Widget (invalid config)

### ISSUE THREAD

**Issue by fsedarkalex** [igorgladkov/rotini#22]
My current problem is that my openhab sometimes does not receive a condition from the server.

I would suggest that you just srite question marks into values not containing any string/number instead of just alerting invalid config.

Btw again my config:
    Frame label="Wetter {widget:weather}" {
      Text item=Weather_CommonId label="{item:condition}"
      Text item=Weather_Condition label="{item:condition-summary}"
      Text item=temp_out label="{item:temperature}"
      Text item=Weather_Temp_Max label="{item:temperature-high}"
      Text item=Weather_Temp_Min label="{item:temperature-low}"
      Text item=hum_out label="{item:humidity}"
    }

CommonId is not always populated - at least as it seems to me...

**Comment by igorgladkov** [comment]
@fsedarkalex What weather provider do you use?
Also, from weather binding wiki it seems like commonId should always be populated, so that might be a bug there.
And finally, invalid config should not be shown just because required item doesn't have a value (uninitialized or similar), so there might be a bug in weather widget as well.

**Comment by fsedarkalex** [comment]
I tried Yahoo and OpenWeatherMap
UPDATE: Btw... It says missing item condition

**Comment by fsedarkalex** [comment]
I checked that again... Weather_ConditionId is at the moment even set to mostly-cloudy-day

I have no idea why your app says invalid config. it did indeed work before. probably it's just an unsupported value?

Or might it be another bug... Another item - condition-summary currently has umlauts ü and ö within... "überwiegend bewölkt"

**Comment by igorgladkov** [comment]
Found the reason for invalid config, it is a bug.
That said, condition item is not supporting all commonId values yet, but it will come soon with updates to weather widgets.

**Comment by fsedarkalex** [comment]
just want to note this aside as you are planning to chang weather widget in general: It would also be cool to have a bigger (or resizable) one here - if not already planned or done

**Comment by fsedarkalex** [comment]
IF you did fix this in 0.2.16 then I have to tell unfortunately it's still there and seems to be related to what value commonId has. some work, some don't (guess widget tells invalid config when condision is a value it does not recognise)

**Comment by fsedarkalex** [comment]
Oh one more question: Does weather widget also support 3x2 sizing? If not -> possible? :)

**Comment by ralle12345** [comment]
I just tested with 3.22 and I still see the bug. I'd also second the wish for a 3x2 widget size.

**Comment by igorgladkov** [comment]
Should be fixed in 0.3.23

**Comment by ralle12345** [comment]
Thanks for the update. Now the widget only shows the weather icon and temperature. But now low/high or other infos privided by other items. 

And - could you also support 2x2 for this widget as well?? I changed the setup and it turns out that  2x2 could fit the new layout quite well :)

**Comment by ralle12345** [comment]
Sorry, I should have read the Release notes first. I'll try again with the correct widgets :)
