### ISSUE TITLE
Random crash 0.2.16

### ISSUE THREAD

**Issue by fsedarkalex** [igorgladkov/rotini#25]
I encountered a random crash.
I left the app open and went away from the tablet. At some point it has randomly crashed as when I returned I had a crash dialog on my screen.

crash report has been sent and should be visible in your google play developer console. I inserted my nickname into comment field.

**Comment by fsedarkalex** [comment]
jfyi: happened again, sent another report through google.

**Comment by fsedarkalex** [comment]
I updatesd openhab to 1.8.0 now crashes happen more often as of my feeling... sent a report again

**Comment by igorgladkov** [comment]
@fsedarkalex do you still experience these crashes?

**Comment by fsedarkalex** [comment]
No crashes since March so far

**Comment by igorgladkov** [comment]
Ok, lots of bugs got fixes in the last few weeks, so this might have been fixed as well.
Will close this now, feel free to reopen if it happens again.
