### ISSUE TITLE
Enhancement: Refresh gesture and button

### ISSUE THREAD

**Issue by fsedarkalex** [igorgladkov/rotini#26]
Any chance you could implement a refresh gesture (overpulling from top) and button (in menu) that will act like swicthing sitemap to another and back?
I mean completely reloading the sitemap including values...

**Comment by igorgladkov** [comment]
Is it because you need to refresh after changes on the server?
I don't really see the need for it during normal app operation since widgets should refresh automatically and it would just clatter UI.

**Comment by fsedarkalex** [comment]
No it has other thoughts behind.
-Changes in Sitemap
-After a connection outage
Generally if something goes wrong it is a quick "escape"

Probably one of both methods is enough of thats a concern

**Comment by igorgladkov** [comment]
On second point, refresh after connection outage will be handled automatically in the future (not released yet)

**Comment by fsedarkalex** [comment]
Should server push already work? Fir me it doesnt. What might be the issue here?
Btw it does also not work with habdroid for me but dont know if it should...

**Comment by igorgladkov** [comment]
It should, but not in the cases when sitemap is modified manually. AFAIK OpenHAB server do not report those.

**Comment by slu125** [comment]
Server push is not working for me either.

**Comment by igorgladkov** [comment]
@slu125 to clarify, when an item state is changed through any other means, the app widget is not changing?

**Comment by fsedarkalex** [comment]
@igorgladkov For me when I change the state of a switch on openhabs web frontend the item on project rotini does not get an update even after minutes. Same goes for temperature items.

**Comment by slu125** [comment]
@igorgladkov exactly.
