### ISSUE TITLE
Widgets do not auto-update in certain installs

### ISSUE THREAD

**Issue by igorgladkov** [igorgladkov/rotini#28]
See more in https://github.com/igorgladkov/rotini/issues/26

**Comment by d0t101101** [comment]
Same problem over here.  Tested this while having the standard OpenHAB Web UI/HABDroid/Rotini open side by side.  An outbound phone call triggers the desired switch which almost immediately takes effect on Web UI/HABDroid, however even after as the phone call continues for a while nothing is updated on Rotini.  Same issue seems to effect other switches too, as others reported.  Manually refreshing the sitemap by switching to another and back, the switch in Rotini shows the correct state, however!

If its of any help to narrow it down, I am using OH/Rotini without SSL (for testing) on standard ports, and all internal so I'm certain a network appliance cannot be interfering...

**Comment by d0t101101** [comment]
To add to that - the quickest way to replicate this is on my dashboard, which has an 'all lights' group:

```
     Frame label="All Lights {widget:light-switch}" {
      Switch item=Lights
     }
```

And my Asterisk call item:

```
 Text label="Telecom" {
    Frame label="{widget:switch}" {
    Text item=Incoming_Call
  }
```

Are all out of sync compared to other UIs until the sitemap is reloaded.

**Comment by fsedarkalex** [comment]
for me autupdate is fixed in latest version.

**Comment by igorgladkov** [comment]
@fsedarkalex I didn't do any changes related to that, so it might an intermittent issue then. Let me know if it re-appears for you again.

**Comment by fsedarkalex** [comment]
too bad... it worked for some hors and now it is stcuk again. no updates...

**Comment by fsedarkalex** [comment]
I sent you an email with a logcat hopefully it will help

**Comment by slu125** [comment]
I previously had the same problem. I was running a 1.8.0 snapshot version from the 2nd of January 2016. Now I just updated to the release (including all addons). Now updating the states seem to be working fine.

Update:
Seems to happen again, that the values in the app are not updated. I will try to investigate further to give more feedback.

**Comment by igorgladkov** [comment]
It is actually just happened to me as well with existing app install (no changes), so I think there is some intermittent issue with OpenHAB server.

**Comment by anordvall** [comment]
@igorgladkov may I suggest you ask Chris Jackson for server-side help (if needed) to nail down this issue? It seems it causes a lot of strange behavior for all/most of us. I'm sure you can kill this issue off quickly if you work together.

**Comment by igorgladkov** [comment]
@anordvall I believe I saw an issue on OpenHAB github about something similar before, and the outcome was that it wasn't worth fixing it for 1.x, since 2.x moves away from websockets/pull. I will need to find it to see if that's the same issue

**Comment by slu125** [comment]
For me it seems to help, if I also restart openhab after changing the sitemap.

**Comment by anordvall** [comment]
@igorgladkov When using several devices to control your home automation this openHAB 1 bug becomes very noticable. Would it perhaps be possible to somewhat "work around" this bug by adding an option in the settings that makes the current sitemap/tab to refresh at a certain interval? Even the interval could perhaps be made configurable. You could add a note that this setting is only meant to work around this certain websockets/pull bug in openHAB 1.

I would really love to see my wall mounted tablet refresh at least every 30 mins to mitigate this problem. At the moment I have to manually switch back and forth between the current sitemap and one of the other ones.

**Comment by d0t101101** [comment]
+1 - still happens for me with OpenHAB v1.8.1 and the latest version of Rotini.  Sometimes the label updates but the color of the icons do not (reflecting if they are in an off/on state)

**Comment by dholmen** [comment]
+1 An auto-refresh option would be really nice to keep the UI in sync. As it is now, the weather and forecast widgets are pretty useless and having to manually switch sitemaps brings the WAF down quite a lot (and the awesome WAF is what makes Rotini so relevant for many people).

**Comment by igorgladkov** [comment]
@dholmen I would argue that if one need to manually refresh home automation UI, it is failed already. I think all refresh issues will not be applicable to OH2, when it is supported. So, we will see after that, and maybe introduce some workaround solution for OH1 only, until everyone switches to OH2.

**Comment by fsedarkalex** [comment]
My suggestion for a workaround would be this:
Automatically reload all items whenever two conditions are met:
-No item refreshed automatically within last 5 minutes
-No interaction between user and UI has happened within last 30 seconds

**Comment by igorgladkov** [comment]
Sitemaps and items are reloading periodically as of recently. Given that OH1 server bug will not be fixed anyway, closing this
