### ISSUE TITLE
Thermostat widget

### ISSUE THREAD

**Issue by igorgladkov** [igorgladkov/rotini#3]

**Comment by d0t101101** [comment]
+1 - would like to control my Nest via Rotini..

**Comment by boik99** [comment]
Loving Rotini, but the setpoint widget is the one thing holding me back. I use OH to control central heating, solar hot water and irrigation and need to set a few temperatures that control when things happen.

**Comment by fsedarkalex** [comment]
+1 - Any news on this?

**Comment by igorgladkov** [comment]
@fsedarkalex any new widgets will be released only after the new beta.

**Comment by igorgladkov** [comment]
Will be available in 1.0-beta1
