### ISSUE TITLE
Colorpicker enhancements regarding popup dismissal and landscape mode

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#32]
Two suggested low prio enhandcements to the colorpicker:
- Click anywhere outside the popup should close the color picker
- In landscape view on a normal phone, the actual palette gets really small

Suggestion to fix the second item is to move the Close button (or remove it completely if first item is implemented) and/or to make the brightness slider vertical and Place it on the right side of the palette

**Comment by igorgladkov** [comment]
Clicking outside popup does close it for me (tried on few different devices).
Does it not close any popup in the app for you?

**Comment by anordvall** [comment]
No it doesn't... I'm clicking like crazy. Weird? :)

**Comment by anordvall** [comment]
No it doesn't. I've tried with the color picker popup, the theme selector popup and Voice Command Item setting popup. None of them close when clicking outside.

**Comment by igorgladkov** [comment]
What device/OS?

**Comment by anordvall** [comment]
Samsung Galaxy S4 with Android 5.0.1

**Comment by igorgladkov** [comment]
Created new issue for palette size: https://github.com/igorgladkov/rotini/issues/33

**Comment by anordvall** [comment]
Verified that the color picker popup can now be closed. Thanks for the fix!
