### ISSUE TITLE
widget-generic

### ISSUE THREAD

**Issue by d0t101101** [igorgladkov/rotini#39]
Feature request for a simple 'widget:generic' to display text/images in the Rotini UI as a flat widget without any additional functionality (for now).  For example, here is the sitemap definition for my UPS monitoring:

```
   Text label="Batteries" {
      Frame label="UPS1 Battery {widget:battery}" {
        Text item=UPS1_Battery_Charge
      }
     Frame label="UPS1 Temp {widget:temperature}" {
        Text item=UPS1_Temp label="{item:temperature}"
     }
     Frame label="UPS1 Status {widget:generic}" {
        Image url="http://google.com/test.jpg"
        Text item=UPS1_Status
     }
    }
```

The idea is that the raw image and plain text of the UPS1_Status item would be displayed 'as is' with no additional functionality.  This would be helpful for not only displaying raw data, but potentially debugging the sitemap/items too.

**Comment by igorgladkov** [comment]
There are already separate "text" and "image" widgets, so this should be covered.

I added it to wiki as well:
- https://github.com/igorgladkov/rotini/wiki/Text-Widget
- https://github.com/igorgladkov/rotini/wiki/Image-Widget

**Comment by anordvall** [comment]
@igorgladkov , I would like to have this generic widget request reopened. What I would like is to have a generic widget that looks like e.g. the temperature widget with:
- headline text
- text for the value

Use case examples:

| Power consumption |
| --- |
| 542 W |

| Door open counter |
| --- |
| 750 times |

| Aurora Borealis Forecast |
| --- |
| Kp 0.67 |

etc etc etc.

What do you Think? Perhaps just add the posibility of a "text for the value" to the text widget and it would be all done?

**Comment by igorgladkov** [comment]
@anordvall I'm not sure I understand how is this different from current Text widget? What do you mean by "text for the value"?

**Comment by anordvall** [comment]
@igorgladkov The temperature widget has two labels. One for the headline and one for the actual temperature. As far as I know, the text widget can only display one label. Right?

To turn this around, how can I configure the text widget to make it look like a temperature widget (for example)?

**Comment by anordvall** [comment]
@igorgladkov Never mind! I didn't think before I wrote the message. The text widget does exactly what I want. Sorry for the confusion :)

**Comment by igorgladkov** [comment]
@anordvall np
