### ISSUE TITLE
OpenHAB 2 support

### ISSUE THREAD

**Issue by igorgladkov** [igorgladkov/rotini#4]

**Comment by MrMontesa** [comment]
OH2 will have a powerful restAPI that might be interesting for this ticket.
https://www.eclipse.org/smarthome/rest/index.html

**Comment by tavalin** [comment]
Given that the OH2 beta was just released, where does OH2 support sit on the priority list now?

**Comment by therealtobo** [comment]
This ticket hasn't been commented on in a while and I'm wondering the same thing, any news/plans with regards to OH2?

**Comment by igorgladkov** [comment]
There are plans, but no news at this moment.
It seems to me that even though OH2 beta was released it still lacks in some areas (docs in particular), so I'm not in rush to jump on it.

**Comment by therealtobo** [comment]
I understand, hopefully they'll spruce up the documentation shortly. Been reading up on Rotini alot lately and I'm very keen on starting to use it :)

**Comment by igorgladkov** [comment]
@therealtobo Are you using OH2 as your main setup?

**Comment by therealtobo** [comment]
@igorgladkov Yessir

**Comment by tavalin** [comment]
I'm using OH2 as my main setup also :)

**Comment by florpan** [comment]
+1 on OH2 as main setup

**Comment by MHerbst** [comment]
I have also switched to openHab2

**Comment by d0t101101** [comment]
After testing OH2 I am also considering making the switch, but am hesitating due to losing my beloved Rotini UI!
+1

**Comment by igorgladkov** [comment]
Released in 0.4.31

**Comment by hakan42** [comment]
Cool :smiling_imp:

**Comment by therealtobo** [comment]
Nice, will try it out this week!
