### ISSUE TITLE
Configure which of the available sitemaps to list in the menu

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#45]
If you have several tablets and phones, it would be useful if you could decide (from app settings) which of the available sitemaps will actually be shown in the app menu.

E.g. a wall mounted tablet in the living room should have access to:
- Livingroom tablet sitemap
- Rooms sitemap

... but not have access to:
- Bedroom tablet sitemap

With such a feature you can reduce the amount of "noise" and allow for quicker access to the sitemaps you actually care about.

**Comment by igorgladkov** [comment]
This is in development

**Comment by therealtobo** [comment]
Please add sorting as well as the ordering might be an intricate part of the layout.

**Comment by igorgladkov** [comment]
Not applicable to the new beta anymore.
