### ISSUE TITLE
Mode widget - Different image/icon depending on selected mode

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#46]
To make it super quick to see the selected mode of a Mode widget, it would be good if you can configure different image URLs / Icons for the different modes.

For example:

A burglar alarm Mode widget could be set to "Off", "Perimeter alarm", "Full alarm". Currently the config would for instance be:

```
Number  AlarmMode
```

...

```
Frame label="{widget:mode}" {
    Image url="http://some.url.here/alarm.png"
    Selection item=AlarmMode mappings=[
    0="Off",
    1="Perimeter alarm",
    2="Full alarm"
    ]
}
```

However, it would be good if these can be used:

0 - Image url="http://some.url.here/alarm-off.png"
1 - Image url="http://some.url.here/alarm-perimeter.png"
2 - Image url="http://some.url.here/alarm-full.png"

**Comment by igorgladkov** [comment]
Mode widget now supports separate icons for all modes.
