### ISSUE TITLE
Mode widget - Allow configuration to disable popup and instead loop through modes

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#47]
If you have a very simple Mode widget you might not want/need a popup with the available modes. Instead, when clicking on the Mode widget it could just loop through the available modes.

E.g. an alarm widget shown on a tablet in the bedrom could for instance have the modes "Off" and "Perimeter alarm". To allow quick access, the mode could just immediately change once you click on the widget.

**Comment by anordvall** [comment]
Just an idea; Perhaps even make it possible to hold down on the widget and it will loop one step at a time with e.g. a delay of 1 second between each mode, and when you release it will select the mode.

**Comment by igorgladkov** [comment]
Mode widget will support _spinner_ config in the next release.
Example of config:

```
Frame label="{widget:mode,spinner:true}" {
  Selection item=ModeAlarm mappings=[
    armed="Armed {icon:lock}",
    home="At home {icon:home}",
    disarmed="Disarmed {icon:unlock}"
  ]
}
```

**Comment by anordvall** [comment]
Verified to work with the latest release. Thanks!
