### ISSUE TITLE
Rollershutter widget

### ISSUE THREAD

**Issue by MrMontesa** [igorgladkov/rotini#5]
A rollershutter widget would be awsome in my environment. There are several implementation ways.
The most straight forward might be a simple switch with definable upper & lower value so that the rollershutter cycles between those values if push-button is pressed.

The more advanced implementation would be kind of vertical dimmer, where you can set the level of the shutter.

Best would be to combine both in one widget. Short-press cycles between two levels. While long-press gives you access to more granular adjustments.
Let me know if I can be of any help.

**Comment by anordvall** [comment]
Igor, I feel bad for asking... but any idea when this widget will be available? A big part of my home automation is the rollershutters so this widget would really make my day :)

**Comment by MrMontesa** [comment]
Same with me :smile: 
I have 12 rollershutter at home so this will be the most used widget in my setup.
Would dramatically increase the [WAF](https://en.wikipedia.org/wiki/Wife_acceptance_factor)
Thanks much

**Comment by igorgladkov** [comment]
@anordvall it is one the next widgets to get released, but I need to work out some app-wide user experience before it would be ready, so I don't know how is it going to be time-wise.

**Comment by anordvall** [comment]
Excellent :+1: Btw, two wishes:
- the icon should indicate whether the rollershutter is closed, partially open or fully open
- there should be a stop button that immediately stops the rollershutter

**Comment by therealtobo** [comment]
+1

**Comment by MrMontesa** [comment]
Hey Igor,
may I ask how deep this is burried in the backlog? Any plans to create such widget soon?
This is really the last bit missing before I can convince my wife to swtich to Rotini.
I'm more than happy if I can assist in creating such widget.
Thanks much!

**Comment by igorgladkov** [comment]
@MrMontesa If no unexpected problems, rollershutter widget should actually be up for a release very soon

**Comment by igorgladkov** [comment]
There are some issues with rollershutter widget, so it will not be released just yet, but it is still one of the next ones to go out.

**Comment by MrMontesa** [comment]
Hey @igor,
Thanks for keeping us posted. Hoping the best for the next releases. 
Keep up the good work.

**Comment by anordvall** [comment]
@igorgladkov, the summer and the sun is here and the need for this widget is getting stronger :) Do you have any ETA to share?

**Comment by igorgladkov** [comment]
@anordvall No ETA at this point. There were issues with this widget so it is held back for a bit.

**Comment by LKuech** [comment]
+1

**Comment by anordvall** [comment]
Igor, can you share any details of the problems? Maybe someone can help out with ideas? :)

**Comment by igorgladkov** [comment]
Experimental version of this widget is added in 0.22.
Not all requests listed above are in that first version, but it will be enhanced at later stages. I will close this generic request, so please open separate feature requests as needed.

Also, if your OH server is routinely stops sending events to UI this widget will misbehave more than others, since it depends heavily on correct current states to show its controls.
