### ISSUE TITLE
Widget does not size to fill content appropriately

### ISSUE THREAD

**Issue by jokeman3000** [igorgladkov/rotini#50]
text gets cut off in both landscape and portrait.

Using latest (.2.20) on a oneplus one

![screenshot_2016-01-16-15-05-40](https://cloud.githubusercontent.com/assets/16737597/12374506/e2c13f3e-bc62-11e5-9a47-1b7f4c6a0011.png)

**Comment by igorgladkov** [comment]
I did get reports of this one on some other phones as well, but I couldn't reproduce it yet. I'm working on some changes on widget sizing, so let's see if it still a problem after it is implemented.

**Comment by igorgladkov** [comment]
@jokeman3000 can you check if the latest version (0.5.41) still has an issue? it had changes related to widget layout which could have hopefully fix this.

**Comment by igorgladkov** [comment]
No response - closing. Feel free to reopen if the issue is still unfixed.
