### ISSUE TITLE
Crash when loading a sitemap with backdrop

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#51]
Both my tablet and phone crashes when I switch to a sitemap that has a backdrop configured as:

Image label="{item:backdrop}" url="https://source.unsplash.com/category/nature/1600x900"

A report has been sent with my nickname in the title.

**Comment by frode** [comment]
You're too quick @anordvall ! Good one.

**Comment by igorgladkov** [comment]
Fixed in 0.3.22
