### ISSUE TITLE
Backdrop improvement: Add url for vertical and horizontal orientation

### ISSUE THREAD

**Issue by frode** [igorgladkov/rotini#55]
Add two url options example:

Image label="{item:backdrop}" vertical-url="https://source.unsplash.com/category/nature/1080x1920, horizontal-url="https://source.unsplash.com/category/nature/1920x1080"

And automatically use the correct one for the current orientation :+1: 

url as it is in the current version could be used as a fallback if none of the orientations were specified.

**Comment by igorgladkov** [comment]
Are you using backdrop on a phone or handheld tablet?

**Comment by d0t101101** [comment]
I'm using Rotini on all my devices, and would also like to see this proposed feature to switch the image based on orientation (mostly for Phone's).

**Comment by igorgladkov** [comment]
@frode, @d0t101101 To restate my question, are you using the same sitemap with backdrop on all devices (phones and tablets)?

**Comment by d0t101101** [comment]
Yes, I am...  Portriat mode truncates the backdrop image on both.

**Comment by frode** [comment]
@igorgladkov I use one sitemap on both phone and tablet, and will make a dedicated table sitemap later when you release a android 4.x compatible app, or when I've purchased a newer tablet for the purpose.

**Comment by igorgladkov** [comment]
Added in 0.3.26

**Comment by frode** [comment]
@igorgladkov Well done, any info om usage?

**Comment by igorgladkov** [comment]
@frode Will update the wiki closer to release time

**Comment by frode** [comment]
@igorgladkov A bit early in the morning here, not completed my first coffee cup yet. Thanks, release numbers slipped my eyes.

**Comment by d0t101101** [comment]
@igorgladkov - thanks for the new feature!  Tested and working fine.  A potential feature improvement around this - can you parameterize the devices width/height?  This way the resolution can be detected by Rotini and passed in as variables to the image URL, so the same sitemap would be pixel perfect on many devices...

For example:

Image label="{item:backdrop}" vertical-url="https://source.unsplash.com/category/nature/{device:width}x{device:height}"

**Comment by igorgladkov** [comment]
@d0t101101 I would say just set the highest resolution you need from all your devices and it will be down-sampled whenever required, which should not have any quality loss.
