### ISSUE TITLE
Label in switch using a transform/MAP file does not update properly

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#56]
If you have a switch using a MAP file, e.g:

```
    Switch  Light_GF_Livingroom_Spotlights  "Spotlights [MAP(sv.map):%s]"
```

The state (in this case "PÅ" and "AV") does not update when you toggle the switch. You need to manually reload the sitemap for it to update. The same switch but without any MAP-file works fine and updates immediately on toggle.

My sitemap contains:

```
    Frame label="Spotlights {widget:light-switch}" {
        Text item=Light_GF_Livingroom_Spotlights
    }
```

**Comment by igorgladkov** [comment]
Does that switch without MAP updates when you toggle it from classic UI or HABDroid?

**Comment by anordvall** [comment]
Weird. I restarted the client and then everything worked as expected. Then I restarted it again and now the same problem exists. None of my switches now updates in Rotini when I toggle them from HABDroid.

So, this might be related to #28 ?

**Comment by anordvall** [comment]
OK so they don't even update in HABdroid now. I've had this issue back and forth in the HABDroid client since I started with openHAB last summer and it's SO annoying.

So, I assume the English ON & OFF are local strings in the client while my mapped strings are fetched from the sever at each toggle? And if issue 28 exists then it will not update the label. If this is correct then please feel free to close this issue report.

**Comment by anordvall** [comment]
Now for some reason it started to work both in HABbdoid and Rotini at the same time, So I'll close this issue. I also see there is a slight delay of updating my mapped labels while the ON & OFF labels are instant, so I assume my last guess was correct.

**Comment by igorgladkov** [comment]
@anordvall Yes, you are correct, unless text value is specified in sitemap it uses local strings. I had the same happened to my OpenHAB yesterday, it stopped updating for a few hours and then worked again, so it seems like server issue.
Also, if you only used MAP to translate values that would not be needed when the app is translated itself for simple ON/OFF cases.

**Comment by anordvall** [comment]
OK good to know I'm not alone with that issue :)

My device language is set to Swedish. Still, "ON" and "OFF" are not translated. Any idea what might be the cause of that?

**Comment by igorgladkov** [comment]
Oh, the app is only English for now, but I do plan more languages down the road.

**Comment by anordvall** [comment]
Right, I'll use MAP for the time being then :) Please let me know if you want help with Swedish translations and I will be happy to help out.
