### ISSUE TITLE
[Webview Widget] Add JavaScript support

### ISSUE THREAD

**Issue by slu125** [igorgladkov/rotini#57]
It would be great if the Webview widget would support the execution of Javascript.

A use case for me is to display current departures from my local subway stop. I fetch the data for this dynamically via Javascript.

I run the app on wall mounted tablets.

**Comment by igorgladkov** [comment]
:+1: for use case

On a side note: it would be cooler to fetch the current departures through OpenHAB (depends on the page format of course), then you can actually have some triggers based on the schedule, as well as showing HTML page without JS

**Comment by slu125** [comment]
I currently use this project (https://github.com/kr1sp1n/bvg-api) to fetch the data for my station. The returned JSON I can probably put into OpenHAB. Also like the idea about triggering rules.

**Comment by frode** [comment]
I am also waiting for this.. it makes sense to load data into openhab from external services, but many times that also results in some hacking/reverse engineering of a web solution that doesnt provide open or easy access to the data sources. 

My use case:
I would like to display bus scheduling information on a dedicated tab, this way anyone in the house that is planning to travel by bus can simply peek at the bus schedule tab and get a precise info on when the next buses are traveling from our area in to town or the other way around.

**Comment by d0t101101** [comment]
I also want this - my use case is for embedding the KODI web UI for browsing media and controlling instances...

**Comment by tbrandstetter** [comment]
+1 it's also necessary for Grafana charts until it's possible to have a native charts widget.

**Comment by d0t101101** [comment]
+1 on using this for embedding Grafana charts - tried that weeks ago and couldn't because of the lack of JS script support...

**Comment by frode** [comment]
There will be many use cases where it makes sense to pull a "light" html/js page from other systems and present them in the app/widget view. I already have 3 different views that is quite lightweight and makes much sense to directly display in a widget rather than putting the data in openhab items.

**Comment by frode** [comment]
http://developer.android.com/reference/android/webkit/WebSettings.html#setJavaScriptEnabled(boolean)

**Comment by igorgladkov** [comment]
@frode not sure what you mean by that link

**Comment by frode** [comment]
@igorgladkov Sorry, I forgot to add my question. Could it be that simple to set JavaScriptEnabled on the WebSettings of the WebView?

**Comment by igorgladkov** [comment]
@frode there are other technical concerns to be address such as scaling if all webpages to be supported. And that's only if supporting all webpages makes sense. By definition, embedding a page alters user experience. To be honest, I'm not convinced that webpages should be included at all yet. There is always a balance between customizability and coherent user experience, so this is something that needs more time to be decided.

**Comment by frode** [comment]
@igorgladkov arent the scaling issue already the same for all web views with or without javascript enabled? I can imagine that pages that require JS to function properly should enable more pages to render better fitted than without JS enabled..

**Comment by igorgladkov** [comment]
@frode Yes, but JS allows to use more pages that most of the time aren't in control of a user, so it become more important issue. Also, page responsiveness to mobile screen should not depend on JS, so that shouldn't matter for rendering.

**Comment by igorgladkov** [comment]
Added. Will be available in the new beta.
