### ISSUE TITLE
new widget for caldav

### ISSUE THREAD

**Issue by MrMontesa** [igorgladkov/rotini#58]
A Calendar widget would be awsome.
I'm using the newly available caldav bindings from 1.8 to pull appointments from my ownCloud calendar.
Having a widget that can show the next X ammount of upcoming appointments would be great.

My use-case:
I'm displaying the upcoming next 3 appointments for the week in OH. There every appointment consists of 2 items. A DateTime when the appointment is and a string item with the subject of the appointment.

The widget should be configured to use those item pairs to nicely display upcoming events.
Let me know if you have any questions.

**Comment by igorgladkov** [comment]
:+1: for including use case

**Comment by csowada** [comment]
That would be great, my tablet is mounted on the floor and should show up the next appointments.
I currently use the text widget, but the text size is to big to show all information.

**Comment by querdenker2k** [comment]
+1

**Comment by igorgladkov** [comment]
Added in 0.4.39
