### ISSUE TITLE
Thermostat, AC, Heatpump Widget

### ISSUE THREAD

**Issue by johgum-zz** [igorgladkov/rotini#63]
Suggestion to a new Widget. 
Power (On, Off)
Freeze Protection (On, Off)
Target temperature (17 - 31)
Mode (Dry, Heat, Cool, Fan, Auto)
Fans peed (1 - 4)

**Comment by anordvall** [comment]
+1 for this one

Though, I personally dont't need freeze protection (?) so good if it's optional to see it in the widget.

**Comment by frode** [comment]
+1

**Comment by johgum-zz** [comment]
@anordvall In freeze protection mode, the heatpump overrides the setting for indoor temperature and regulate it to approximately 8 °C. In this way you can protect your home/cabin from freezing during cold periods at the lowest possible power consumption

**Comment by anordvall** [comment]
Ok. Optional then, as I don't have a cabin :)

**Comment by johgum-zz** [comment]
Some inspiration perhaps

https://user.intesishome.com/panel

**Comment by igorgladkov** [comment]
Will be available in 1.0-beta1
