### ISSUE TITLE
Weather widget - Add unit for wind speed and make wind direction optional

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#64]
To make it consistent and easier to understand, please add a unit for the wind speed in the advanced weather widget.

Also, it would be good if wind direction can be made optional since it's far from as useful to know as e.g. the wind speed.

I.e. make it possible to have wind as e.g:

"5 m/s" and/or "5 m/s WSW"

**Comment by igorgladkov** [comment]
Added in 0.3.27
