### ISSUE TITLE
Weather_Condition problem

### ISSUE THREAD

**Issue by d0t101101** [igorgladkov/rotini#67]
Hi,

My Rotini.sitemap definition for the Weather widget looks like this:

```
    Frame label="New York {widget:weather-advanced,size:2x2}" {
  Text item=Weather_Condition label="{item:condition}"
  Text item=Weather_Temp label="{item:temperature}"
  Text item=Weather_Precip_Total label="{item:precipitation}"
  Text item=Weather_Humidity label="{item:humidity}"
  Text item=Weather_Wind label="{item:wind-speed}"
  Text item=Weather_Wind_Direction label="{item:wind-direction}"
  Text item=Weather_Temp_Dewpoint label="{item:dewpoint}"
  Text item=Weather_Pressure label="{item:pressure}"
  Text item=Weather_Visibility label="{item:visibility}"
}
```

Everything works except for Weather_Condition, which shows up as 'N/A' in Rotini.  I'm using the Wunderground API, and can see the item does in fact have a value in HABDroid - at the moment its 'Overcast'...

I'm running the very latest version of the app (v0.3.24).  Wondering if Rotini expects a certain list of 'condition' mappings!

**Comment by igorgladkov** [comment]
Is Weather_Condition bound to text or commonId?

**Comment by d0t101101** [comment]
That was it, thanks!  It was bound to text with this in my main items configuration:
     `String   Weather_Condition        "Condition [%s]"      <sun_clouds> {weather="locationId=home, type=condition, property=text"}``

So I simply switched it to CommonId and it works:
     `String   Weather_CommonId         "Common id [%s]"      {weather="locationId=home, type=condition, property=commonId"}`    

Consider this case closed :)
