### ISSUE TITLE
Music widget - Album cover not always loaded

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#69]
Igor, I made the change to the Album Cover rule as we earlier discussed, e.g. having only:

```
rule "Album Cover"
    when
        Item Sonos_GF_Livingroom_Album changed
    then
...
```

However, still the album cover is not always loaded.

Example 1:
Hey Brother - Avicii By Avicii
Avicii

Log:

2016-01-29 23:14:43.215 [ERROR] [o.o.c.t.actions.Transformation] - Error executing the transformation 'JSONPATH': An error occured while transforming JSON expression.
2016-01-29 23:14:43.215 [INFO ] [enhab.model.script.org.openhab] - requestUrl: https://api.spotify.com/v1/search?type=album&q=Avicii+True%3A+Avicii+By+Avicii
2016-01-29 23:14:43.215 [INFO ] [enhab.model.script.org.openhab] - coverUri: {
  "albums" : {
    "href" : "https://api.spotify.com/v1/search?query=Avicii+True%3A+Avicii+By+Avicii&offset=0&limit=20&type=album",
    "items" : [ ],
    "limit" : 20,
    "next" : null,
    "offset" : 0,
    "previous" : null,
    "total" : 0
  }
}

Example 2:
Be Mine!
Robyn

Log:

2016-01-29 23:15:58.330 [ERROR] [o.o.c.t.actions.Transformation] - Error executing the transformation 'JSONPATH': An error occured while transforming JSON expression.
2016-01-29 23:15:58.330 [INFO ] [enhab.model.script.org.openhab] - requestUrl: https://api.spotify.com/v1/search?type=album&q=Robyn+Cool+-+R%26B
2016-01-29 23:15:58.335 [INFO ] [enhab.model.script.org.openhab] - coverUri: {
  "albums" : {
    "href" : "https://api.spotify.com/v1/search?query=Robyn+Cool+-+R%26B&offset=0&limit=20&type=album",
    "items" : [ ],
    "limit" : 20,
    "next" : null,
    "offset" : 0,
    "previous" : null,
    "total" : 0
  }
}

**Comment by igorgladkov** [comment]
@anordvall When cover is not loaded what does it show in UI? old cover or empty?

**Comment by anordvall** [comment]
@igorgladkov it becomes empty.

**Comment by igorgladkov** [comment]
That's actually good and expected behavior.
In terms of those covers:
- Robyn one is actual has no results, so empty cover is okay (rule might need to be modified to avoid the error)
- Avicii had colon (:) char in the name, which I think confuses spotify API as well, if colon removed results are good. Probably worth stripping characters from track/album/artist names in the rule

**Comment by anordvall** [comment]
Weird, I could see the Robyn cover in my SONOS app... but perhaps it was something cached? I can't even find it anymore :)

There are a lot of songs that does not show the cover... but perhaps stripping characters as you suggest will solve the problem for most/all of them. Will you update the rule on the wiki?

**Comment by igorgladkov** [comment]
For Robyn cover, what is the exact album name?

Yes, will update a bit later.

**Comment by anordvall** [comment]
It's called "Cool - R&B"

**Comment by igorgladkov** [comment]
That explains it - it could find "Cool", but not "Cool - R&B"

**Comment by igorgladkov** [comment]
@anordvall 0.3.26 version has support for client-side cover updates, so you are not required to use _cover_ item anymore

**Comment by anordvall** [comment]
Thanks! =)
