### ISSUE TITLE
Weather & forecast widgets - icons changes color

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#70]
After leaving the app running for a short while, the icons in the weather and forecast widgets turns gray/brown. See attached screenshot.

Reproduced on Android 5.0.2

![brown icons](https://cloud.githubusercontent.com/assets/13090236/12694504/a6fbbf82-c730-11e5-844e-42abcae5705b.png)

**Comment by igorgladkov** [comment]
@anordvall is this on Samsung device?

**Comment by anordvall** [comment]
It's on an ASUS tablet.

// Andreas
Den 5 apr. 2016 9:02 AM skrev "Igor Gladkov" notifications@github.com:

**Comment by igorgladkov** [comment]
Fixed in 0.5.41
