### ISSUE TITLE
A widget to show Number items

### ISSUE THREAD

**Issue by TommySharpNZ** [igorgladkov/rotini#73]
I'm looking for a way to show generic numbers as a widget. Being able to specify a "unit" of measure would be ideal so you could display things like....
75kgs
235L

My use case would be to show the last weight in Kg that my FitBit scale has posted to openHAB.

**Comment by anordvall** [comment]
You can use the text widget for this.

**Items:**
Number  FitBit_Scale_Weight "[%d kg]"

**Sitemap:**
Frame label="Weight {widget:text}" {
    Text item=FitBit_Scale_Weight
}

**The widget would display e.g:**

Weight
78 kg

Of course, it would be super nice if the widget would support an optional Icon or Image URL.

**Comment by TommySharpNZ** [comment]
Thanks the "text" widget does work well enough for now. Did try and use the "icon" setting as below but it doesn't seem to work at the moment so being able to set an image would be great...

Frame label="Tommy {widget:text}" icon="kitchen" {
        Text item=FitBit_Weight_Tommy
        }

The fitbit scale also tracks body fat% so it would be cool to be able to display this extra detail in the one widget. Probably not a specific "scale" widget but maybe even a text widget where you can define the main text item and also 2 smaller ones that appear at the bottom left and right of the widget. That could be quite useful...

**Comment by tbrandstetter** [comment]
+1 
@igorgladkov what would be useful is a "generic" widget which can be used for various use cases. For example like the temperature or the weather advanced widget. Thus, we could create widgets own our own for:
- heatpumps
- power consumption

and so on. An example would be:

Frame label="Heat pump {widget:generic}" {
  Text item=Heatpump_Status_Actual label="{item:own_icon_for_it}"
  Text item=Heatpump_Starts label="{item:own_icon_for_it}"
  Text item=Heatpump_Runtime label="{item:own_icon_for_it}"
}

**Comment by anordvall** [comment]
+1 for generic widgets = more freedom.

**Comment by igorgladkov** [comment]
Added in 0.4.37
