### ISSUE TITLE
Weather widget without weather binding with custom values

### ISSUE THREAD

**Issue by igorgladkov** [igorgladkov/rotini#74]
Ben Jones:

> I don't use the weather binding, so don't have a condition-id, but do have a condition text item which I query from the Wunderground HTTP service. All the sensor values come from my custom weather station (temp, humidity, pressure and rainfall).
> 
> Is there any chance you could allow the various sensor values to be optional in the weather-advanced widget? In my case there would be no wind-speed or wind-direction since my custom weather station doesn't report these.
> 
> Currently I can only use the basic weather widget, and all it shows is temp, since I have no condition-id.

**Comment by sumnerboy12** [comment]
As mentioned in the openHAB forum, all I need is to make the various sensor readings optional - i.e. the wind values which I don't have available. Cheers!

**Comment by igorgladkov** [comment]
@sumnerboy12 In 0.3.27 wind-direction item is optional, so you can workaround wind-speed requirement by supplying placeholder item `Text label="{item:wind-speed} [Undefined]"`, it will show N/A in UI.
Weather widget is limited to 3 or 6 extra reading now, so making some of them optional is not feasible yet.

**Comment by sumnerboy12** [comment]
Yep - that worked - thanks Igor!!

**Comment by igorgladkov** [comment]
Will be available in 1.0-beta1
