### ISSUE TITLE
Hue HSB Values?

### ISSUE THREAD

**Issue by d0t101101** [igorgladkov/rotini#76]
Igor,

How did you derive the HSB values used for the new advanced lighting widget's moods?

https://github.com/igorgladkov/rotini/wiki/Light-Color-Advanced-Widget

Curious as to where you got these numbers, and if they match what the Philips Hue app tries to do (beyond the Cinema mode)...

```
Frame label="Living Room {widget:light-color-advanced}" {
  Colorpicker item=Light_Color_Living_Room
  Text label="{item:preset1} [185.1,13.7,100]"
  Text label="{item:preset2} [185.9,16.1,100]"
  Text label="{item:preset3} [44.6,32.2,100]"
  Text label="{item:preset4} [44.7,43.1,100]"
  Text label="{item:preset5} [7.1,82.5,40.4]"
}

```

Thank you much,
.

**Comment by igorgladkov** [comment]
I took it from Hue web portal, so they should be the same as in the Hue app, although I didn't confirm it specifically.

**Comment by d0t101101** [comment]
Thanks - some slight discrepancies were noticed when comparing them between Rotini/Hue (specifically for the concentrate/focus and relax modes).  While not identical to the Hue app, your HSB color codes are much better than what I was previously using :)

Consider this closed! 

Best regards,
.
