### ISSUE TITLE
Visibility in weather optional

### ISSUE THREAD

**Issue by mlava** [igorgladkov/rotini#78]
Hi Igor.
Having a ball playing with my sitemaps.
Visibility is not available in my area, so I wonder if it could be optional in weather widgets?
Cheers!

**Comment by igorgladkov** [comment]
Since there is fixed number of spaces in Weather widget, optionality is not possible at this moment.
As I mentioned in #74, you can workaround by using `Text label="{item:visibility} [Undefined]"` to show N/A in UI.

**Comment by mlava** [comment]
Thanks Igor. 
Sorry I missed #74.
Cheers

**Comment by mlava** [comment]
Thanks Igor. 
Sorry I missed #74.
Cheers
