### ISSUE TITLE
Items don't get updated

### ISSUE THREAD

**Issue by igorgladkov** [igorgladkov/rotini#79]
From Martin G ([original](https://plus.google.com/103407136888880800329/posts/QP6KnSKx9B7)):

> I have very often the problem that items didn't get updated. (analog values stuck on an old value)
> 
> Also minimize and reopen doesnt change that behavior. Only killing the app and restart it solve the problem.
> But after some time the problem come again...
> 
> Any ideas?

**Comment by csowada** [comment]
Me too

**Comment by fsedarkalex** [comment]
didn't we discuss that before and see that it is an issue at OH?

**Comment by igorgladkov** [comment]
@fsedarkalex yes, but sitemap should get reloaded when app is reopened regardless, so this might be a different issue

**Comment by tavalin** [comment]
@igorgladkov what's the current expected behaviour when items are updated in OH outside of Rotini? Should the values in Rotini automatically update?

**Comment by igorgladkov** [comment]
@tavalin yes, but OH1 server does have some issues with pushing updates to clients. So it does not work for everyone every time.

**Comment by tavalin** [comment]
I'm on OH2 and noticed that the state doesn't change i.e. widgets keep the same state when changed outside of Rotini.

**Comment by igorgladkov** [comment]
OH2 works for me without any issues.
Does it happen when app open for awhile or at any time?

**Comment by tavalin** [comment]
It was happening always.  However I've just changed the server info and tried again and it is working.

**Comment by igorgladkov** [comment]
>  I've just changed the server info

What do you mean by that?

**Comment by tavalin** [comment]
Went to the left hand menu and clicked server settings and changed them so Rotini used the LAN address of the OH server instead of the remote DNS host I had set up.

After that I tried again with both LAN and dynamic DNS addresses and both worked.

**Comment by arch1v1st** [comment]
> "Went to the left hand menu and clicked server settings and changed them so Rotini used the LAN address of the OH server instead of the remote DNS host I had set up.
> After that I tried again with both LAN and dynamic DNS addresses and both worked."

@tavalin - thanks, but I have been running against the internal IP:port (not DNS) for a long time now and still experiencing the same issue.  Wondering if the problem returns after some time has passed for you too!

**Comment by fsedarkalex** [comment]
For me it never worked until i switched from a virtual machine to a physical device.
Since I am using the physical device now it works most of the time and just stops refreshing once or twice within 24 hours so it seems to be related to networking or timing issues.
Please  see my last comment on #28:

> My suggestion for a workaround would be this:
> Automatically reload all items whenever two conditions are met:
> -No item refreshed automatically within last 5 minutes
> -No interaction between user and UI has happened within last 30 seconds

**Comment by raffaeletani** [comment]
can't we have a defineable item, wich gets checked by rotini periodically, and if its state changes, rotini reloads all items?

**Comment by igorgladkov** [comment]
Sitemap should be reloading now on app open
