### ISSUE TITLE
new "empty" widget for basic ordering in frontend

### ISSUE THREAD

**Issue by MrMontesa** [igorgladkov/rotini#8]
With an empty widget I would be able to force linebreaks and blanks in my frontend. This would help to better order the items the way I like it.

Use case:
light items are in row 1
Rollershutters should be in row 2

You have to "fill up" row 1 to force a linebreak and continue with rollershutters in row 2.

**Comment by anordvall** [comment]
I would also find this useful now when using the app on a 10" tablet. Of course, you could add a spacer by using:

```
Frame label="{widget:text}" {
    Text label=""
}
```

... but it leaves a widget background color. It would be nicer if it was completely empty and show the app background color.

**Comment by tbrandstetter** [comment]
+1 this would bring some flexibility for bigger screens

**Comment by TommySharpNZ** [comment]
Yeah, in this case my layout would look better with a "blank" widget the the right of the "gate" which would make the cameras show up nicely on their own line..

![screenshot_2016-05-17-09-23-28](https://cloud.githubusercontent.com/assets/15130284/15305102/3bd3c404-1c15-11e6-9d10-9bc7543d71bf.png)

**Comment by tiny-tinker** [comment]
Note that using this widget:

```
    Frame label="{widget:text}" {
        Text item=""
    }
```

Results in a tile with a title of `(no title)`. :(

**Comment by igorgladkov** [comment]
@nomadic-squirrel I believe there is a workaround that some users use to specify empty space in label: `Text label=" "`. I'm not officially suggesting that, but it should work in the mean time :)

**Comment by tiny-tinker** [comment]
ahhh yes, duh. `label`, not `item`. That works!

**Comment by igorgladkov** [comment]
Not applicable to the new beta version. Closing
