### ISSUE TITLE
garage-door widget no longer working in 0.3.28

### ISSUE THREAD

**Issue by TommySharpNZ** [igorgladkov/rotini#80]
Hi Igor, this widget below used to work until I upgraded last night. I get an Invalid Config error saying the state of "CLOSED" is not valid.

I'm guessing you're doing some changes on this widget?

Frame label="Garage 1 {widget:garage-door}" {
        Switch item=Contact_B_GarageDoor1
        }

**Comment by igorgladkov** [comment]
@TommySharpNZ How do use this widget, is it a switch or contact for garage door?
There was a bug before that contact item was accepted for switches, which is not correct since contact items don't receive commands.

**Comment by TommySharpNZ** [comment]
Hi Igor it was just a contact to show the open/close status.... Works again if I change it to a window widget.

**Comment by TommySharpNZ** [comment]
Hi Igor it was just a contact to show the open/close status.... Works again if I change it to a window widget.

**Comment by igorgladkov** [comment]
Great, there is actually generic binary-sensor widget so you can use custom icon, that would be preferable to window-sensor in this case.
