### ISSUE TITLE
Feature request : PIN secured mode widget (or all widgets accepting input)

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#81]
Please extend the possibility of PIN security to all widgets that can be interacted with. I'm especially concerned that the mode widget does not support PIN. The mode widget is the only widget available that supports several alarm states such as for instance "off, perimeter alarm and full alarm"

**Comment by arch1v1st** [comment]
+1 - Scene widget PINs would be my #1 use case for this cool new feature!

**Comment by TommySharpNZ** [comment]
+1 for pin security on Mode Widgets please....

**Comment by rossdargan** [comment]
+1 It's probably the only widget I have that needs it!

**Comment by igorgladkov** [comment]
PIN security for Mode widget has been added in 0.5.45
