### ISSUE TITLE
Have music widget support Player item

### ISSUE THREAD

**Issue by therealtobo** [igorgladkov/rotini#82]
For the squeezebox OH2 binding there are no separate controls for play/pause/next etc but rather a Player item that supports all of these actions. It would be great if the music widget could support this item.

Reference:
https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.squeezebox

**Comment by igorgladkov** [comment]
Another info: https://community.openhab.org/t/understanding-oh2-paperui-by-sonos-channel-item/8461﻿

**Comment by igorgladkov** [comment]
Added in 0.4.33

**Comment by therealtobo** [comment]
Nice one Igor, will try it out as soon as the new milestone is released and the Wiki is updated with the new widget conf :)
