### ISSUE TITLE
Filter out non-Rotini

### ISSUE THREAD

**Issue by therealtobo** [igorgladkov/rotini#83]
I think it would be nice if Rotini only displayed compatible sitemaps. The best approach in my book would be that the user sets a flag or similar in the beginning of the file in order to tag it as "to be displayed in Rotini". This way you would still see sitemaps that might have other errors - good for troubelshooting. The OH default sitemaps wouldn't be included. The user could choose to "hide" sitemaps that are work in progress or similar from the UI.

**Comment by therealtobo** [comment]
Also, it should be configurable in which order the sitemaps are displayed in Rotini. Either it's "random" at the moment or I'm not getting the sorting. Either way, it should be possible to state something like

sitemap overview label="Overview" order="1" {

to get this one to display at the top of the list.

**Comment by tbrandstetter** [comment]
I think this should be handled by Issue #45

**Comment by therealtobo** [comment]
I might be inclined to agree with you, especially if sorting etc added as functionality as well. It might make for a smoother solution to do this using the app as described in Issue #45.
