### ISSUE TITLE
Icon support for button widget

### ISSUE THREAD

**Issue by therealtobo** [igorgladkov/rotini#84]
It would be nice to be able to set an icon for the button widget. I've tried icon="garage" without any luck for example, is it supposed to be working already or future enhancement?

**Comment by arch1v1st** [comment]
Please share a snippet of your sitemap entries, 'icon' is working for me!

**Comment by therealtobo** [comment]
Two examples below, maybe I was a bit hasty and this FR only applies for button-on/off and not the "regular" button?

Frame label="{widget:button-on}" icon="window" {
Frame label="{widget:button-off}" icon="garage" {

**Comment by therealtobo** [comment]
@igorgladkov 

Also, I'm guessing that maybe this should be closed, on/off buttons should be removed in the future and this ticket would sort that instead? Makes for a more flexible solution :)

https://github.com/igorgladkov/rotini/issues/86

**Comment by igorgladkov** [comment]
@therealtobo Can you explain the use case you have that you using buttons for? It seems to me that this looks more like a switch

**Comment by therealtobo** [comment]
Well, for the garage for example it only sends an "on" command on the KNX bus and that toggles the door. There is no up/down or similar. So, every time i push this button I want it to send a 1 on that KNX GA.

**Comment by therealtobo** [comment]
Have you had a chance to look at this? Right now the button works but looks very dull since I can't select an icon for it.

**Comment by igorgladkov** [comment]
Added in 0.14

**Comment by therealtobo** [comment]
Works, thanks @igorgladkov
