### ISSUE TITLE
UNDEF state "breaks" music and light-dimmer widgets

### ISSUE THREAD

**Issue by therealtobo** [igorgladkov/rotini#85]
The pioneer AVR binding returns UNDEF for volume and mute when receiver is powered off, this makes the widgets I've tried out (music and light-dimmer) display an error icon with the text "unknown state UNDEF"

Also, in order for the widget to be displayed after switching on the receiver i need to leave that page or sitemap and return again, then it looks as it should again.

**Comment by igorgladkov** [comment]
I don't have pioneer device myself, so can't test this out. So to confirm, volume and mute returns "UNDEF" as a string value when it is off, which is not the same as OpenHAB standard "Uninitialized" or "Undefined" or "NULL" values?

**Comment by therealtobo** [comment]
Would it work with NULL then? I'm def ok with trying to make the devs change it to that if it makes more sense from an OH (OH2) perspective.

**Comment by igorgladkov** [comment]
I would ask someone from OH dev team to confirm, but standard undefined value is "Undefined" so I would expect all bindings to use that. "Uninitialized" (OH1) or "NULL" (OH2) is only when state wasn't assigned yet at all, like after server restart, so I think it shouldn't be used in this case.

**Comment by igorgladkov** [comment]
@therealtobo it seems like Undefined has been changed to UNDEF in OH2, will confirm that later. Are you using OH2?

**Comment by therealtobo** [comment]
@igorgladkov I'm using OH2, the reason for switching over was actually this binding as the pioneer binding in 1.x is broken in terms of having multiple receivers. So, then UNDEF might be correct and should be supported in OH2.

**Comment by igorgladkov** [comment]
Fixed in 0.4.36

**Comment by therealtobo** [comment]
@igorgladkov Seems to be working fine now, thanks!
