### ISSUE TITLE
Mappings should be possible for switches/buttons etc

### ISSUE THREAD

**Issue by therealtobo** [igorgladkov/rotini#86]
It should be possible to use mappings to create custom states/functions for widgets like switches and buttons etc.

One example I was using in habdroid looks as follows:
Switch  item=LivingRC_Vol icon="" label="Volume" mappings=[DECREASE="-", INCREASE="+"]

**Comment by igorgladkov** [comment]
Button command mapping added in 0.14

**Comment by therealtobo** [comment]
Works, thanks @igorgladkov
