### ISSUE TITLE
Color Fading

### ISSUE THREAD

**Issue by fsedarkalex** [igorgladkov/rotini#87]
That's a request:
I would love to see a fading implemented. I think of smooth fadings from current to selected color.
I don't know if openhab api can handle that much commands coming in within a second but if then this would be a great feature.

The fading should be configurable in a time of milliseconds. so I can configure like that: Color will fad to new selection within 2 seconds.

**Comment by arch1v1st** [comment]
I would love to see this too, but it probably needs to be implemented at the Hue binding level at not in Rotini itself!

**Comment by fsedarkalex** [comment]
Hue binding is definitely the wrong place.
If openhab it would had to be implemented within the colorpicker item
