### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by welbymcroberts** [igorgladkov/rotini#9]
Implement the ability to display charts within the application

Potentially allow a widget to be pressed (Short/Long press/ Double tap?) to "pop up" the chart.

Support more than just RRD4J for source for graphs (don't rely on the RRD4J "rrdchart.png" for generating the charts.

**Comment by frode** [comment]
I would suggest to access the openhab rest api for retrieving persistence data, similar to how chris is doing it in habmin (habminurlpath/persistence/charts). Perhaps there is some code examples in the habmin project.

**Comment by igorgladkov** [comment]
Yep, the charts do (when released) work through rest API.

**Comment by tbrandstetter** [comment]
Good to hear. Today I played with the Openhab build in functionality (which creates only a Png). This looks ugly. It would be nice, if the diagrams widgets could also have a clean transparent look. Maybe you can make it configurable if someone likes to have a grid behind a diagram or not. And last but not least - a fill option for this would be awesome.

**Comment by tbrandstetter** [comment]
As an alternative - today I played a little bit with the Influxdb persistence binding. Influxdb has also a nice way how to query the data and get back json data:

https://docs.influxdata.com/influxdb/v0.9/guides/querying_data/

**Comment by anordvall** [comment]
If possible, please implement a way to filter out spikes, either by just skipping the spike values or by forcing a Y-axis range so the spikes at least don't ruin the chart. At least when using RRD4J this is a big problem as afaik you can't manually edit the data.

![5766d177606ae26d6de9099794c06a3e3bbcf294](https://cloud.githubusercontent.com/assets/13090236/17153129/49e60c30-537b-11e6-8ddc-c71a7b302a95.png)

**Comment by igorgladkov** [comment]
https://plus.google.com/107943099010507170951/posts/irRPeuZY6DX

> Its been brought up elsewhere, and I would also like to see charts implemented natively in Rotini.  I personally use them in OpenHAB for many chart-able metrics - Temps/Humidity/Wind for instance.  This can be accomplished today though with the following in your sitemap, but native implementation via a widget could offer a lot more:
> 
> ```
> Frame label="{widget:web}" {
>   Webview url="/chart?groups=Weather_Chart_Temp&period=h" 
> }
> ```
> 
> OR (albeit some sizing/dimension issues depending on the client device):
> 
> ```
> Frame label="{widget:image}" {
>   Image url="/chart?groups=Weather_Chart_Temp&period=h" refresh=10000
> }
> ```
> 
> Best regards,

**Comment by igorgladkov** [comment]
Moving to the new community: https://community.projectrotini.com/t/charts-widget/397
