### ISSUE TITLE
Switch widget results in application crash

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#94]
Since latest version (I believe) Rotini instantly crashes when trying to load a sitemap containing a switch widget. This is my setup that makes it crash on several devices:

**Items:**
`Switch Settings_Enable_Staircase_Alarm         "Larm för trappgrindar"                <settings>  (Settings)`

**Sitemap:**

```
sitemap tablet_livingroom label="Tablet - Vardagsrum"
{
        Frame label="Trappgrind larm {widget:switch}" {
            Switch item=Settings_Enable_Staircase_Alarm
        }
}
```

**Comment by igorgladkov** [comment]
That's because switch widget doesn't have default icon, so if it cannot find a supported icon on either widget config or item it would crash. Crash is already fixed in the next version (releasing today), but you would still need to have icon config set, otherwise, it will just use a placeholder icon.

**Comment by igorgladkov** [comment]
@anordvall before previous release, that switch widget was completely missing icon in UI, correct?

**Comment by anordvall** [comment]
@igorgladkov it had a filled circle as icon. Is that the placeholder Icon I can expect after the fix? I assume you don't have a "settings" icon available? :)

**Comment by igorgladkov** [comment]
@anordvall no, it would more of the warning icon. What is that "settings" icon represent in this case, is it generic setting or specific to some domain?

**Comment by anordvall** [comment]
@igorgladkov a generic settings icon would be nice to have and could cover a lot of different settings. I would suggest a gear icon for this purpose. My current settings are:
- enable alarm for child gates/doors in the staircase
- automatically control rollershutters
- automatically control dollhouse light
- automatically control lavalamp light

More settings will be added from time to time .. :)

**Comment by anordvall** [comment]
Also, I believe a good default icon for a switch widget would be as the previous behavior. I.e. an empty circle when it was off and filled circle when it was on.

**Comment by igorgladkov** [comment]
The thing is that previous behavior was not indented and was a bug, but I will consider switch-specific default icon for these cases.

Closing this since original bug is fixed.

**Comment by anordvall** [comment]
For how it looked previously:
https://plus.google.com/111923515631072106738/posts/Zd3aGQ8NvxY
(widget in the middle with title "Trappgrind larm")
