### ISSUE TITLE
Request: Custom titles on gauges/gauge group items

### ISSUE THREAD

**Issue by frode** [igorgladkov/rotini#97]
If you have example a group of different gauges displaying similar data presented for total cpu usage, but also cpu usage for a specific process (Example openHAB), there is no way to easily distinguish these two.. ?

Guess I could use multiple gauge groups with different titles ..

**Comment by igorgladkov** [comment]
No, not really. Gauge Group by design contains items that don't need specific titles, because those could be easily created with standalone Gauge widget.
Would that work for you?

**Comment by igorgladkov** [comment]
@frode New Linear Gauge Group widget allows to have both icons and labels on each gauge, which should cover this use case.

**Comment by frode** [comment]
Thanks, it indeed cover this use case!
