### ISSUE TITLE
Gauge widget error: invalid state

### ISSUE THREAD

**Issue by MrMontesa** [igorgladkov/rotini#98]
Hey,
I've setup a gauge widget as below and receive error message of "invalid state". Mut I think the state value is ok. Here's the config:

`Frame label="Rolladen Büro {widget:gauge}" {
Text item=eg_Rolladen_Buero label="{unit:%,icon:garage}"
}
`

And this is the item polled via rest api:

`
<item>
<type>RollershutterItem</type>
<name>eg_Rolladen_Buero</name>
<state>80</state>
<link>http://nuc:8080/rest/items/eg_Rolladen_Buero</link>
</item>`

As you can see the state is 80 which should be ok for gauge percentage, right?
Do you see any config errors?
Let me know if yo need more info.
Thanks much

**Comment by igorgladkov** [comment]
Rollershutter item is not fully supported yet, I wasn't adding support until specific widget is ready, but it shouldn't need to depend on it, so I can add item support earlier.

**Comment by MrMontesa** [comment]
That would be highly appreciated. Until rollershutter widget is supported, I'm going to use a button-on widget to start the rollershutters based on some rules I coded in OH backend. In addition I'd like to see the level of the shutters. Thus using the new gauge widget.

Btw: Having a rollershutter icon would be great too.
Thanks much.

**Comment by igorgladkov** [comment]
Added in 0.22
