### ISSUE TITLE
[BUG] Icons disappearing in gauge-group

### ISSUE THREAD

**Issue by hmerk** [igorgladkov/rotini#99]
I just tried the new gauge-group widget on a fresh openHAB2 installation.
When I jump to the page containing this widget, I can see the icons for about 3 seconds and then they disappear.

**Comment by igorgladkov** [comment]
What is the device and OS?

**Comment by igorgladkov** [comment]
Fixed in 0.5.41

@hmerk Can you please confirm after the release. Thanks

**Comment by hmerk** [comment]
Thanks Igor,
just checked a different device, so I see it already worked on Android 5.1 but not on 5.0.1

Best
Hans-Jörg
